import { LanguageCode } from "../types";

// Clear, app-like hero for every tool — mobile first
// Tells the user in 3 seconds: what is this, what does it do, is it free?

interface ToolHeroInfo {
  icon: string;
  name: string;
  tagline: string;
}

const HERO_DATA: Record<string, Partial<Record<LanguageCode, ToolHeroInfo>>> = {
  humanizer: {
    en: { icon: "✨", name: "AI Text Humanizer", tagline: "Make robotic text sound natural and human" },
    es: { icon: "✨", name: "Humanizador de Texto", tagline: "Haz que el texto robótico suene natural" },
    ur: { icon: "✨", name: "AI Text Humanizer", tagline: "Robotic tehreer ko insani andaaz dein" },
    de: { icon: "✨", name: "Text-Humanizer", tagline: "Robotext natürlich klingen lassen" },
    fr: { icon: "✨", name: "Humaniseur de Texte", tagline: "Rendez le texte robotique naturel" },
    tr: { icon: "✨", name: "Metin İnsancıllaştırıcı", tagline: "Robotik metni doğal hale getirin" },
    pt: { icon: "✨", name: "Humanizador de Texto", tagline: "Torne o texto robótico natural" },
    ja: { icon: "✨", name: "テキストヒューマナイザー", tagline: "ロボット的な文章を自然に" },
    no: { icon: "✨", name: "Tekst-Humanizer", tagline: "Gjør robottekst naturlig" },
    nl: { icon: "✨", name: "Tekst-Humanizer", tagline: "Maak robottekst natuurlijk" },
    it: { icon: "✨", name: "Umanizzatore di Testo", tagline: "Rendi naturale il testo robotico" },
    ru: { icon: "✨", name: "ИИ-гуманизатор", tagline: "Сделайте текст человечным" },
    "ur-pk": { icon: "✨", name: "اے آئی ٹیکسٹ ہیومنائزر", tagline: "مشینی متن کو قدرتی انسانی لکھائی بنائیں" },
  },
  detector: {
    en: { icon: "🔍", name: "AI Content Detector", tagline: "Check which sentences sound AI-written" },
    es: { icon: "🔍", name: "Detector de IA", tagline: "Revisa qué frases suenan a IA" },
    ur: { icon: "🔍", name: "AI Content Detector", tagline: "Check karen konsa jumla AI jaisa lagta hai" },
    de: { icon: "🔍", name: "KI-Detektor", tagline: "Prüfen welche Sätze KI-like klingen" },
    fr: { icon: "🔍", name: "Détecteur IA", tagline: "Vérifiez les phrases qui sonnent IA" },
    tr: { icon: "🔍", name: "AI İçerik Dedektörü", tagline: "Hangi cümlelerin yapay olduğunu kontrol edin" },
    pt: { icon: "🔍", name: "Detector de IA", tagline: "Verifique frases com cara de IA" },
    ja: { icon: "🔍", name: "AI検出ツール", tagline: "AIっぽい文をチェック" },
    no: { icon: "🔍", name: "AI-Detektor", tagline: "Sjekk hvilke setninger som høres AI ut" },
    nl: { icon: "🔍", name: "AI-Detector", tagline: "Check welke zinnen AI-achtig klinken" },
    it: { icon: "🔍", name: "Rilevatore IA", tagline: "Controlla le frasi che sembrano IA" },
    ru: { icon: "🔍", name: "Детектор ИИ", tagline: "Проверьте текст на нейросеть" },
    "ur-pk": { icon: "🔍", name: "اے آئی مواد شناخت کار", tagline: "جانچیں کون سے جملے اے آئی جیسے لگتے ہیں" },
  },
  citation: {
    en: { icon: "📚", name: "Citation Generator", tagline: "Create APA, MLA, Chicago references in seconds" },
    es: { icon: "📚", name: "Generador de Citas", tagline: "Crea referencias APA, MLA en segundos" },
    ur: { icon: "📚", name: "Citation Generator", tagline: "APA, MLA hawale secondon mein banayen" },
    de: { icon: "📚", name: "Zitationsgenerator", tagline: "APA, MLA Referenzen in Sekunden" },
    fr: { icon: "📚", name: "Générateur de Citations", tagline: "Créez des références APA, MLA" },
    tr: { icon: "📚", name: "Kaynakça Oluşturucu", tagline: "Saniyeler içinde APA, MLA kaynakçası" },
    pt: { icon: "📚", name: "Gerador de Citações", tagline: "Crie referências APA, MLA em segundos" },
    ja: { icon: "📚", name: "引用ジェネレーター", tagline: "APA、MLA引用を数秒で作成" },
    no: { icon: "📚", name: "Siteringsgenerator", tagline: "Lag APA, MLA referanser på sekunder" },
    nl: { icon: "📚", name: "Citatiegenerator", tagline: "Maak APA, MLA referenties in seconden" },
    it: { icon: "📚", name: "Generatore di Citazioni", tagline: "Crea citazioni APA, MLA in secondi" },
    ru: { icon: "📚", name: "Генератор цитирования", tagline: "Ссылки APA, MLA и ГОСТ" },
    "ur-pk": { icon: "📚", name: "حوالہ بنانے والا", tagline: "APA، MLA، شکاگو حوالے لمحوں میں بنائیں" },
  },
  expander: {
    en: { icon: "📝", name: "Sentence Expander", tagline: "Turn short sentences into detailed paragraphs" },
    es: { icon: "📝", name: "Expansor de Oraciones", tagline: "Convierte frases cortas en párrafos" },
    ur: { icon: "📝", name: "Sentence Expander", tagline: "Chhote jumlon ko tafseeli paragraph banayen" },
    de: { icon: "📝", name: "Satz-Expander", tagline: "Kurze Sätze zu Absätzen erweitern" },
    fr: { icon: "📝", name: "Expanseur de Phrases", tagline: "Développez des phrases en paragraphes" },
    tr: { icon: "📝", name: "Cümle Genişletici", tagline: "Kısa cümleleri paragrafa dönüştürün" },
    pt: { icon: "📝", name: "Expansor de Frases", tagline: "Transforme frases em parágrafos" },
    ja: { icon: "📝", name: "文拡張ツール", tagline: "短文を詳細な段落に" },
    no: { icon: "📝", name: "Setningsutvider", tagline: "Gjør korte setninger til avsnitt" },
    nl: { icon: "📝", name: "Zinsuitbreider", tagline: "Maak van zinnen alinea's" },
    it: { icon: "📝", name: "Espansore di Frasi", tagline: "Trasforma frasi in paragrafi" },
    ru: { icon: "📝", name: "Расширитель текста", tagline: "Увеличьте объём текста" },
    "ur-pk": { icon: "📝", name: "جملہ پھیلانے والا", tagline: "چھوٹے جملے تفصیلی پیراگراف بنائیں" },
  },
  summarizer: {
    en: { icon: "📄", name: "Text Summarizer", tagline: "Shrink long articles into key points" },
    es: { icon: "📄", name: "Resumidor de Texto", tagline: "Resume artículos largos en puntos clave" },
    ur: { icon: "📄", name: "Text Summarizer", tagline: "Lambi tehreer ka khulasa banayen" },
    de: { icon: "📄", name: "Text-Zusammenfasser", tagline: "Lange Artikel zusammenfassen" },
    fr: { icon: "📄", name: "Résumeur de Texte", tagline: "Résumez les longs articles" },
    tr: { icon: "📄", name: "Metin Özetleyici", tagline: "Uzun yazıları özetleyin" },
    pt: { icon: "📄", name: "Resumidor de Texto", tagline: "Resuma textos longos" },
    ja: { icon: "📄", name: "要約ツール", tagline: "長文を要点にまとめる" },
    no: { icon: "📄", name: "Tekstsammendrag", tagline: "Forkort lange artikler" },
    nl: { icon: "📄", name: "Tekstsamentatter", tagline: "Vat lange teksten samen" },
    it: { icon: "📄", name: "Riassuntore", tagline: "Riassumi articoli lunghi" },
    ru: { icon: "📄", name: "Сокращатель текста", tagline: "Краткое содержание текста" },
    "ur-pk": { icon: "📄", name: "اے آئی متن خلاصہ کار", tagline: "کسی بھی متن کا خلاصہ لمحوں میں" },
  },
  voiceTyping: {
    en: { icon: "🎙️", name: "Voice Typing", tagline: "Speak and watch your words become text" },
    es: { icon: "🎙️", name: "Dictado por Voz", tagline: "Habla y mira cómo tus palabras se escriben" },
    ur: { icon: "🎙️", name: "Voice Typing", tagline: "Bolen aur alfaz khud text ban jayen" },
    de: { icon: "🎙️", name: "Spracheingabe", tagline: "Sprechen statt tippen – Worte werden Text" },
    fr: { icon: "🎙️", name: "Saisie Vocale", tagline: "Parlez et vos mots deviennent du texte" },
    tr: { icon: "🎙️", name: "Sesli Yazma", tagline: "Konuşun, sözleriniz yazıya dönüşsün" },
    pt: { icon: "🎙️", name: "Digitação por Voz", tagline: "Fale e suas palavras viram texto" },
    ja: { icon: "🎙️", name: "音声入力", tagline: "話すだけで文字になる" },
    no: { icon: "🎙️", name: "Stemmeskriving", tagline: "Snakk og se ordene bli til tekst" },
    nl: { icon: "🎙️", name: "Spraaktypen", tagline: "Spreek en je woorden worden tekst" },
    it: { icon: "🎙️", name: "Dettatura Vocale", tagline: "Parla e le parole diventano testo" },
    ru: { icon: "🎙️", name: "Голосовой ввод", tagline: "Диктуйте и получайте текст" },
    "ur-pk": { icon: "🎙️", name: "بول کر لکھنا", tagline: "بولیں اور آپ کے الفاظ خود متن بن جائیں" },
  },
  audioToText: {
    en: { icon: "🎧", name: "Audio to Text Converter", tagline: "Turn recordings into text — right on your device" },
    es: { icon: "🎧", name: "Convertidor de Audio a Texto", tagline: "Convierte grabaciones en texto en tu dispositivo" },
    ur: { icon: "🎧", name: "Audio to Text Converter", tagline: "Awaz ko text mein badlen — seedha apne device par" },
    de: { icon: "🎧", name: "Audio zu Text Konverter", tagline: "Aufnahmen direkt auf Ihrem Gerät in Text verwandeln" },
    fr: { icon: "🎧", name: "Convertisseur Audio en Texte", tagline: "Transformez vos enregistrements en texte sur votre appareil" },
    tr: { icon: "🎧", name: "Sesten Metne Dönüştürücü", tagline: "Kayıtları cihazınızda metne çevirin" },
    pt: { icon: "🎧", name: "Conversor de Áudio para Texto", tagline: "Transforme gravações em texto no seu dispositivo" },
    ja: { icon: "🎧", name: "音声テキスト変換", tagline: "録音を端末上でそのままテキストに" },
    no: { icon: "🎧", name: "Lyd til Tekst", tagline: "Gjør opptak om til tekst på enheten din" },
    nl: { icon: "🎧", name: "Audio naar Tekst", tagline: "Zet opnames op je apparaat om in tekst" },
    it: { icon: "🎧", name: "Audio in Testo", tagline: "Trasforma le registrazioni in testo sul tuo dispositivo" },
    ru: { icon: "🎧", name: "Аудио в текст", tagline: "Расшифровка аудио онлайн" },
    "ur-pk": { icon: "🎧", name: "آڈیو سے متن کنورٹر", tagline: "ریکارڈنگ کو متن میں بدلیں — سیدھا اپنے آلے پر" },
  },
  backgroundRemover: {
    en: { icon: "✨", name: "Background Remover", tagline: "Remove image background instantly in your browser using AI." },
    es: { icon: "✨", name: "Quitafondos IA", tagline: "Elimina el fondo de fotos al instante en tu navegador." },
    tr: { icon: "✨", name: "Arka Plan Silici", tagline: "Fotoğrafların arka planını tarayıcınızda anında kaldırın." },
    de: { icon: "✨", name: "Hintergrund Entferner", tagline: "Bildhintergrund direkt im Browser mit KI entfernen." },
    fr: { icon: "✨", name: "Effaceur de Fond", tagline: "Supprimez le fond de vos images directement en ligne." },
    pt: { icon: "✨", name: "Removedor de Fundo", tagline: "Remova o fundo de imagens instantaneamente com IA." },
    ja: { icon: "✨", name: "背景透過ツール", tagline: "AIがブラウザ上で写真の背景を瞬時に消去します。" },
    ur: { icon: "✨", name: "Background Remover", tagline: "Apni photo ka background apney browser mein AI se hatayein." },
    no: { icon: "✨", name: "Bakgrunnsfjerner", tagline: "Fjern bakgrunnen på bildene dine i nettleseren med KI." },
    nl: { icon: "✨", name: "Achtergrond Gum", tagline: "Verwijder foto-achtergronden direct in je browser met AI." },
    it: { icon: "✨", name: "Rimuovi Sfondo", tagline: "Scontorna le foto direttamente nel browser con l'IA." },
    ru: { icon: "✨", name: "Удаление фона", tagline: "Уберите фон с фото" },
    "ur-pk": { icon: "✨", name: "پس منظر ہٹانے والا", tagline: "تصویر کا پس منظر براؤزر میں ہٹائیں" },
  },
  museAiHub: {
    en: { icon: "🌍", name: "Muse AI Availability Checker", tagline: "Check if Meta's Muse AI is officially available in your country" },
    es: { icon: "🌍", name: "Verificador de disponibilidad de Muse AI", tagline: "Comprueba si Muse AI de Meta está disponible oficialmente en tu país" },
    ur: { icon: "🌍", name: "Muse AI Availability Checker", tagline: "Check karen ke Meta ka Muse AI aap ke mulk mein officially available hai ya nahi" },
    de: { icon: "🌍", name: "Muse AI Verfügbarkeits-Check", tagline: "Prüfen Sie, ob Metas Muse AI in Ihrem Land offiziell verfügbar ist" },
    fr: { icon: "🌍", name: "Vérificateur de disponibilité Muse AI", tagline: "Vérifiez si Muse AI de Meta est officiellement disponible dans votre pays" },
    pt: { icon: "🌍", name: "Verificador de Disponibilidade do Muse AI", tagline: "Veja se o Muse AI da Meta está oficialmente disponível no seu país" },
    it: { icon: "🌍", name: "Verifica disponibilità Muse AI", tagline: "Controlla se Muse AI di Meta è ufficialmente disponibile nel tuo paese" },
    ru: { icon: "🌍", name: "Muse AI", tagline: "Доступность и новости" },
    tr: { icon: "🌍", name: "Muse AI Erişilebilirlik Denetleyicisi", tagline: "Meta Muse AI'nin ülkenizde resmen kullanılabilir olup olmadığını kontrol edin" },
    ja: { icon: "🌍", name: "Muse AI 提供状況チェッカー", tagline: "MetaのMuse AIがあなたの国で公式に利用できるか確認できます" },
    no: { icon: "🌍", name: "Muse AI tilgjengelighetssjekk", tagline: "Sjekk om Metas Muse AI er offisielt tilgjengelig i landet ditt" },
    nl: { icon: "🌍", name: "Muse AI Beschikbaarheidschecker", tagline: "Controleer of Muse AI van Meta officieel beschikbaar is in jouw land" },
    "ur-pk": { icon: "🌍", name: "Muse AI دستیابی", tagline: "Muse AI کی دستیابی کی حیثیت جانچیں" },
  },
  voiceCloner: {
    en: { icon: "🎙️", name: "AI Voice Cloner", tagline: "Clone your voice, or hear text in natural voices — in your browser" },
    es: { icon: "🎙️", name: "Clonador de Voz IA", tagline: "Clona tu voz o escucha textos en voces naturales" },
    ur: { icon: "🎙️", name: "AI Voice Cloner", tagline: "Apni awaaz clone karen ya natural awaazon mein text sunain" },
    de: { icon: "🎙️", name: "KI-Stimmenkloner", tagline: "Klone deine Stimme oder höre Texte in natürlicher Stimme" },
    fr: { icon: "🎙️", name: "Cloneur de Voix IA", tagline: "Clonez votre voix ou écoutez vos textes en voix naturelles" },
    tr: { icon: "🎙️", name: "Yapay Zeka Ses Klonlayıcı", tagline: "Sesinizi klonlayın ya da metinleri doğal seslerle dinleyin" },
    pt: { icon: "🎙️", name: "Clonador de Voz IA", tagline: "Clone sua voz ou ouça textos em vozes naturais" },
    ja: { icon: "🎙️", name: "AIボイスクローナー", tagline: "自分の声をクローン、または自然な声で読み上げ" },
    no: { icon: "🎙️", name: "AI-stemmekloner", tagline: "Klon stemmen din, eller hør tekst med naturlige stemmer" },
    nl: { icon: "🎙️", name: "AI-stemkloon", tagline: "Kloon je stem of luister naar tekst in natuurlijke stemmen" },
    it: { icon: "🎙️", name: "Clonatore Vocale IA", tagline: "Clona la tua voce o ascolta testi in voci naturali" },
    ru: { icon: "🎙️", name: "Клонирование голоса", tagline: "Голоса и свой голос" },
    "ur-pk": { icon: "🎙️", name: "آواز کلون اسٹوڈیو", tagline: "مختلف آوازوں میں متن بول کر سنیں" },
  },
  textToSpeech: {
    en: { icon: "🔊", name: "Text to Speech", tagline: "Hear your text read aloud by your device's voices" },
    es: { icon: "🔊", name: "Texto a Voz", tagline: "Escucha tu texto con las voces de tu dispositivo" },
    ur: { icon: "🔊", name: "Text to Speech", tagline: "Apna text apne device ki awaz mein sunain" },
    de: { icon: "🔊", name: "Text zu Sprache", tagline: "Lassen Sie sich Ihren Text vorlesen" },
    fr: { icon: "🔊", name: "Synthèse Vocale", tagline: "Écoutez vos textes lus à voix haute" },
    tr: { icon: "🔊", name: "Metinden Sese", tagline: "Metninizi cihazınızın sesiyle dinleyin" },
    pt: { icon: "🔊", name: "Texto para Fala", tagline: "Ouça seu texto com as vozes do aparelho" },
    ja: { icon: "🔊", name: "テキスト読み上げ", tagline: "端末の音声でテキストを聞けます" },
    no: { icon: "🔊", name: "Tekst til Tale", tagline: "Hør teksten lest høyt med enhetens stemmer" },
    nl: { icon: "🔊", name: "Tekst naar Spraak", tagline: "Hoor je tekst voorlezen met apparaatstemmen" },
    it: { icon: "🔊", name: "Sintesi Vocale", tagline: "Ascolta i tuoi testi con le voci del dispositivo" },
    ru: { icon: "🔊", name: "Озвучка текста", tagline: "Текст в речь онлайн" },
    "ur-pk": { icon: "🔊", name: "متن سے آواز", tagline: "اپنا متن آلے کی آواز میں بولا ہوا سنیں" },
  },
  wordCounter: {
    en: { icon: "🔢", name: "Word Counter", tagline: "Count words, characters and reading time" },
    es: { icon: "🔢", name: "Contador de Palabras", tagline: "Cuenta palabras, caracteres y tiempo de lectura" },
    ur: { icon: "🔢", name: "Word Counter", tagline: "Alfaz, characters aur parhne ka waqt ginain" },
    de: { icon: "🔢", name: "Wortzähler", tagline: "Wörter, Zeichen und Lesezeit zählen" },
    fr: { icon: "🔢", name: "Compteur de Mots", tagline: "Comptez mots, caractères et temps de lecture" },
    tr: { icon: "🔢", name: "Kelime Sayacı", tagline: "Kelime, karakter ve okuma süresini sayın" },
    pt: { icon: "🔢", name: "Contador de Palavras", tagline: "Conte palavras, caracteres e tempo de leitura" },
    ja: { icon: "🔢", name: "ワードカウンター", tagline: "文字数・語数・読了時間を数える" },
    no: { icon: "🔢", name: "Ordteller", tagline: "Tell ord, tegn og lesetid" },
    nl: { icon: "🔢", name: "Woordenteller", tagline: "Tel woorden, tekens en leestijd" },
    it: { icon: "🔢", name: "Contatore di Parole", tagline: "Conta parole, caratteri e tempo di lettura" },
    ru: { icon: "🔢", name: "Счётчик слов", tagline: "Слова и символы онлайн" },
    "ur-pk": { icon: "🔢", name: "لفظ گننے والا", tagline: "الفاظ، حروف اور پڑھنے کا وقت لائیو گنیں" },
  },
  characterCounter: {
    en: { icon: "🔠", name: "Character Counter", tagline: "Exact characters & platform limits" },
    es: { icon: "🔠", name: "Contador de Caracteres", tagline: "Caracteres exactos y límites sociales" },
    ur: { icon: "🔠", name: "Character Counter", tagline: "Saheeh characters aur platform limits" },
    de: { icon: "🔠", name: "Zeichenzähler", tagline: "Genaue Zeichen & Plattform-Limits" },
    fr: { icon: "🔠", name: "Compteur de Caractères", tagline: "Caractères exacts et limites des plateformes" },
    tr: { icon: "🔠", name: "Karakter Sayacı", tagline: "Birebir karakter ve platform sınırları" },
    pt: { icon: "🔠", name: "Contador de Caracteres", tagline: "Caracteres exatos e limites das plataformas" },
    ja: { icon: "🔠", name: "文字カウンター", tagline: "正確な文字数と各制限をチェック" },
    no: { icon: "🔠", name: "Tegnteller", tagline: "Nøyaktige tegn og grenser" },
    nl: { icon: "🔠", name: "Karakters Tellen", tagline: "Exacte tekens en platformlimieten" },
    it: { icon: "🔠", name: "Contatore Caratteri", tagline: "Caratteri esatti e limiti piattaforme" },
    ru: { icon: "🔠", name: "Счётчик символов", tagline: "Знаки с пробелами и без" },
    "ur-pk": { icon: "🔠", name: "حرف گننے والا", tagline: "حروف درست گنیں اور حد جانچیں" },
  },
  typingTest: {
    en: { icon: "⌨️", name: "Typing Speed Test", tagline: "Check your WPM & accuracy in 11 languages" },
    es: { icon: "⌨️", name: "Test de Velocidad", tagline: "Mide tu velocidad y precisión al escribir" },
    ur: { icon: "⌨️", name: "Typing Speed Test", tagline: "Apni typing speed aur accuracy check karein" },
    de: { icon: "⌨️", name: "Tippgeschwindigkeit", tagline: "WPM & Genauigkeit live messen" },
    fr: { icon: "⌨️", name: "Vitesse de Frappe", tagline: "Mesurez votre vitesse et votre précision" },
    tr: { icon: "⌨️", name: "Yazma Hızı Testi", tagline: "WPM ve doğruluğunuzu ölçün" },
    pt: { icon: "⌨️", name: "Velocidade de Digitação", tagline: "Meça seu PPM e sua precisão" },
    ja: { icon: "⌨️", name: "タイピング速度テスト", tagline: "WPMと正確さをその場でチェック" },
    no: { icon: "⌨️", name: "Skrivehastighet", tagline: "Mål WPM og nøyaktighet direkte" },
    nl: { icon: "⌨️", name: "Typesnelheid Test", tagline: "Meet je WPM en nauwkeurigheid live" },
    it: { icon: "⌨️", name: "Velocità di Digitazione", tagline: "Misura WPM e precisione dal vivo" },
    ru: { icon: "⌨️", name: "Тест печати", tagline: "Скорость набора онлайн" },
    "ur-pk": { icon: "⌨️", name: "ٹائپنگ رفتار ٹیسٹ", tagline: "اپنی WPM اور درستگی ناپیں" },
  },
  caseConverter: {
    en: { icon: "🔤", name: "Case Converter", tagline: "UPPERCASE, lowercase & Title Case in one tap" },    es: { icon: "🔤", name: "Convertidor de Mayúsculas", tagline: "MAYÚSCULAS, minúsculas y Título con un toque" },
    ur: { icon: "🔤", name: "Case Converter", tagline: "UPPERCASE, lowercase aur Title Case ek tap mein" },
    de: { icon: "🔤", name: "Groß-/Kleinschreibung", tagline: "GROSS, klein & Titel mit einem Tippen" },
    fr: { icon: "🔤", name: "Convertisseur de Casse", tagline: "MAJUSCULES, minuscules et Titre en un geste" },
    tr: { icon: "🔤", name: "Büyük Küçük Harf", tagline: "BÜYÜK, küçük ve Başlık tek dokunuşla" },
    pt: { icon: "🔤", name: "Conversor de Maiúsculas", tagline: "MAIÚSCULAS, minúsculas e Título num toque" },
    ja: { icon: "🔤", name: "ケースコンバーター", tagline: "大文字・小文字・タイトルをワンタップで" },
    no: { icon: "🔤", name: "Store Små Bokstaver", tagline: "STORE, små og Tittel med ett trykk" },
    nl: { icon: "🔤", name: "Hoofdletterconverter", tagline: "HOOFDLETTERS, klein en Titel met één tik" },
    it: { icon: "🔤", name: "Convertitore Maiuscole", tagline: "MAIUSCOLO, minuscolo e Titolo con un tocco" },
    ru: { icon: "🔤", name: "Регистр текста", tagline: "Заглавные и строчные буквы" },
    "ur-pk": { icon: "🔤", name: "کیس کنورٹر", tagline: "ایک کلک میں متن کی شکل بدلیں" },
  },
  passwordGenerator: {
    en: { icon: "🔑", name: "Password Generator", tagline: "Strong random passwords, made on your device" },
    es: { icon: "🔑", name: "Generador de Contraseñas", tagline: "Contraseñas aleatorias fuertes, en tu dispositivo" },
    ur: { icon: "🔑", name: "Password Generator", tagline: "Mazboot random password, aap ke device par" },
    de: { icon: "🔑", name: "Passwort Generator", tagline: "Starke Zufallspasswörter, lokal erstellt" },
    fr: { icon: "🔑", name: "Générateur de Mot de Passe", tagline: "Mots de passe aléatoires, sur votre appareil" },
    tr: { icon: "🔑", name: "Şifre Oluşturucu", tagline: "Güçlü rastgele şifreler, cihazınızda" },
    pt: { icon: "🔑", name: "Gerador de Senhas", tagline: "Senhas aleatórias fortes, no seu aparelho" },
    ja: { icon: "🔑", name: "パスワード生成", tagline: "安全なランダムパスワードを端末で作成" },
    no: { icon: "🔑", name: "Passordgenerator", tagline: "Sterke tilfeldige passord, på din enhet" },
    nl: { icon: "🔑", name: "Wachtwoordgenerator", tagline: "Sterke willekeurige wachtwoorden, lokaal" },
    it: { icon: "🔑", name: "Generatore di Password", tagline: "Password casuali sicure, sul tuo dispositivo" },
    ru: { icon: "🔑", name: "Генератор паролей", tagline: "Надёжные пароли онлайн" },
    "ur-pk": { icon: "🔑", name: "پاس ورڈ بنانے والا", tagline: "مضبوط بے ترتیب پاس ورڈ فوراً بنائیں" },
  },
  duplicateLines: {
    en: { icon: "🧾", name: "Remove Duplicate Lines", tagline: "Keep the first copy of every line" },
    es: { icon: "🧾", name: "Eliminar Duplicadas", tagline: "Conserva la primera copia de cada línea" },
    ur: { icon: "🧾", name: "Duplicate Lines", tagline: "Har line ki pehli copy rakhen" },
    de: { icon: "🧾", name: "Doppelte Zeilen Entfernen", tagline: "Erste Kopie jeder Zeile behalten" },
    fr: { icon: "🧾", name: "Supprimer les Doublons", tagline: "Gardez la première copie de chaque ligne" },
    tr: { icon: "🧾", name: "Yinelenen Satırlar", tagline: "Her satırın ilk kopyasını tutun" },
    pt: { icon: "🧾", name: "Remover Duplicadas", tagline: "Mantenha a primeira cópia de cada linha" },
    ja: { icon: "🧾", name: "重複行を削除", tagline: "各行の最初のコピーだけを残す" },
    no: { icon: "🧾", name: "Fjern Duplikater", tagline: "Behold første kopi av hver linje" },
    nl: { icon: "🧾", name: "Dubbele Regels", tagline: "Behoud de eerste kopie van elke regel" },
    it: { icon: "🧾", name: "Righe Duplicate", tagline: "Tieni la prima copia di ogni riga" },
    ru: { icon: "🧾", name: "Дубли строк", tagline: "Удалите повторы строк" },
    "ur-pk": { icon: "🧾", name: "دہرائی سطریں ختم کریں", tagline: "فہرست سے دہرائی سطریں ایک کلک میں ہٹائیں" },
  },
  invisibleCharacter: {
    en: { icon: "👻", name: "Invisible Character", tagline: "Copy blank text & reveal hidden text" },
    es: { icon: "👻", name: "Carácter Invisible", tagline: "Copia texto en blanco y revela lo oculto" },
    ur: { icon: "👻", name: "Invisible Character", tagline: "Blank text copy karein, hidden text dekhein" },
    de: { icon: "👻", name: "Unsichtbares Zeichen", tagline: "Leertext kopieren & Verstecktes prüfen" },
    fr: { icon: "👻", name: "Caractère Invisible", tagline: "Copiez du texte vide, révélez le caché" },
    tr: { icon: "👻", name: "Görünmez Karakter", tagline: "Boş metin kopyalayın, gizliyi görün" },
    pt: { icon: "👻", name: "Caractere Invisível", tagline: "Copie texto em branco e revele o oculto" },
    ja: { icon: "👻", name: "見えない文字", tagline: "空白をコピーし隠れた文字を確認" },
    no: { icon: "👻", name: "Usynlig Tegn", tagline: "Kopier blank tekst og se skjulte tegn" },
    nl: { icon: "👻", name: "Onzichtbaar Teken", tagline: "Kopieer lege tekst, toon verborgen tekens" },
    it: { icon: "👻", name: "Carattere Invisibile", tagline: "Copia testo vuoto e rivela il nascosto" },
    ru: { icon: "👻", name: "Невидимый символ", tagline: "Пустой символ для ника" },
    "ur-pk": { icon: "👻", name: "پوشیدہ حرف", tagline: "پوشیدہ حروف کاپی کریں، خالی متن بنائیں" },
  },
  wordFrequency: {
    en: { icon: "📊", name: "Word Frequency Counter", tagline: "Rank repeated words & phrases" },
    es: { icon: "📊", name: "Frecuencia de Palabras", tagline: "Ordena palabras y frases repetidas" },
    ur: { icon: "📊", name: "Word Frequency Counter", tagline: "Bar bar aane wale alfaz aur phrases dekhen" },
    de: { icon: "📊", name: "Worthäufigkeit", tagline: "Wiederholte Wörter & Phrasen ordnen" },
    fr: { icon: "📊", name: "Fréquence des Mots", tagline: "Classez mots et expressions répétés" },
    tr: { icon: "📊", name: "Kelime Sıklığı", tagline: "Tekrar eden kelime ve ifadeleri sıralayın" },
    pt: { icon: "📊", name: "Frequência de Palavras", tagline: "Classifique palavras e frases repetidas" },
    ja: { icon: "📊", name: "単語頻度カウンター", tagline: "繰り返し語句をランキング" },
    no: { icon: "📊", name: "Ordfrekvens", tagline: "Ranger gjentatte ord og fraser" },
    nl: { icon: "📊", name: "Woordfrequentie", tagline: "Rangschik herhaalde woorden en zinnen" },
    it: { icon: "📊", name: "Frequenza Parole", tagline: "Classifica parole e frasi ripetute" },
    ru: { icon: "📊", name: "Частота слов", tagline: "Повторы слов в тексте" },
    "ur-pk": { icon: "📊", name: "لفظ تکرار گننے والا", tagline: "دیکھیں کون سے الفاظ سب سے زیادہ دہرائے" },
  },
  readingTime: {
    en: { icon: "⏱️", name: "Reading Time Calculator", tagline: "How long to read or say your text" },
    es: { icon: "⏱️", name: "Tiempo de Lectura", tagline: "Cuánto tardas en leer o decir tu texto" },
    ur: { icon: "⏱️", name: "Reading Time Calculator", tagline: "Text parhne ya bolne mein kitna time lagega" },
    de: { icon: "⏱️", name: "Lesezeit Rechner", tagline: "Wie lange Lesen oder Sprechen dauert" },
    fr: { icon: "⏱️", name: "Temps de Lecture", tagline: "Combien de temps pour lire ou dire" },
    tr: { icon: "⏱️", name: "Okuma Süresi", tagline: "Metni okumak veya söylemek ne kadar sürer" },
    pt: { icon: "⏱️", name: "Tempo de Leitura", tagline: "Quanto tempo para ler ou falar o texto" },
    ja: { icon: "⏱️", name: "読了時間計算", tagline: "読む・話す時間の目安" },
    no: { icon: "⏱️", name: "Lesetid Kalkulator", tagline: "Hvor lang tid tar det å lese eller si" },
    nl: { icon: "⏱️", name: "Leestijd Calculator", tagline: "Hoe lang lezen of spreken duurt" },
    it: { icon: "⏱️", name: "Tempo di Lettura", tagline: "Quanto tempo per leggere o dire il testo" },
    ru: { icon: "⏱️", name: "Время чтения", tagline: "Сколько минут читать текст" },
    "ur-pk": { icon: "⏱️", name: "پڑھنے کا وقت", tagline: "متن پڑھنے یا بولنے میں کتنا وقت لگے گا" },
  },
  base64: {
    en: { icon: "🔣", name: "Base64 Encoder & Decoder", tagline: "UTF-8 text, URL-safe mode and clear errors" },
    es: { icon: "🔣", name: "Base64 Codificar/Decodificar", tagline: "UTF-8, URL seguro y errores claros" },
    ur: { icon: "🔣", name: "Base64 Encoder Decoder", tagline: "UTF-8 text, URL-safe mode aur saaf errors" },
    de: { icon: "🔣", name: "Base64 Kodieren/Dekodieren", tagline: "UTF-8, URL-sicher und klare Fehler" },
    fr: { icon: "🔣", name: "Base64 Encoder/Décoder", tagline: "UTF-8, sûr pour URL et erreurs claires" },
    tr: { icon: "🔣", name: "Base64 Kodla/Çöz", tagline: "UTF-8, URL güvenli ve açık hatalar" },
    pt: { icon: "🔣", name: "Base64 Codificar/Decodificar", tagline: "UTF-8, URL seguro e erros claros" },
    ja: { icon: "🔣", name: "Base64変換", tagline: "UTF-8・URLセーフ・分かりやすいエラー" },
    no: { icon: "🔣", name: "Base64 Koding/Dekoding", tagline: "UTF-8, URL-sikker og tydelige feil" },
    nl: { icon: "🔣", name: "Base64 Coderen/Decoderen", tagline: "UTF-8, URL-veilig en duidelijke fouten" },
    it: { icon: "🔣", name: "Base64 Codifica/Decodifica", tagline: "UTF-8, URL safe ed errori chiari" },
    ru: { icon: "🔣", name: "Время чтения", tagline: "Сколько минут читать текст" },
  },
  instagramLineBreak: {
    en: { icon: "📸", name: "Instagram Line Breaks", tagline: "Blank lines that survive the post" },
    es: { icon: "📸", name: "Saltos de Línea Instagram", tagline: "Líneas en blanco que sobreviven al publicar" },
    ur: { icon: "📸", name: "Instagram Line Break", tagline: "Khali lines jo post ke baad bhi rahen" },
    de: { icon: "📸", name: "Instagram Zeilenumbruch", tagline: "Leerzeilen, die den Post überleben" },
    fr: { icon: "📸", name: "Sauts de Ligne Instagram", tagline: "Des lignes vides qui survivent à la publication" },
    tr: { icon: "📸", name: "Instagram Satır Atlama", tagline: "Gönderide kaybolmayan boş satırlar" },
    pt: { icon: "📸", name: "Quebra de Linha Instagram", tagline: "Linhas em branco que sobrevivem à postagem" },
    ja: { icon: "📸", name: "Instagram改行", tagline: "投稿しても消えない空行" },
    no: { icon: "📸", name: "Instagram Linjeskift", tagline: "Tomme linjer som overlever innlegget" },
    nl: { icon: "📸", name: "Instagram Regelafbreking", tagline: "Lege regels die de post overleven" },
    it: { icon: "📸", name: "Interruzioni Instagram", tagline: "Righe vuote che restano dopo la pubblicazione" },
    ru: { icon: "📸", name: "Абзацы для Instagram", tagline: "Переносы строк в посте" },
    "ur-pk": { icon: "📸", name: "انسٹاگرام سطر وقفہ", tagline: "کیپشن میں سطر وقفے برقرار رکھیں" },
  },
  jsonFormatter: {
    en: { icon: "🧩", name: "JSON Formatter", tagline: "Beautify, minify & validate JSON" },
    es: { icon: "🧩", name: "Formateador JSON", tagline: "Embellece, minifica y valida JSON" },
    ur: { icon: "🧩", name: "JSON Formatter", tagline: "JSON beautify, minify aur validate karen" },
    de: { icon: "🧩", name: "JSON Formatter", tagline: "JSON formatieren, minifizieren & validieren" },
    fr: { icon: "🧩", name: "Formateur JSON", tagline: "Embellir, minifier et valider le JSON" },
    tr: { icon: "🧩", name: "JSON Biçimlendirici", tagline: "JSON güzelleştir, küçült ve doğrula" },
    pt: { icon: "🧩", name: "Formatador JSON", tagline: "Embelezar, minificar e validar JSON" },
    ja: { icon: "🧩", name: "JSONフォーマッター", tagline: "JSONを整形・圧縮・検証" },
    no: { icon: "🧩", name: "JSON-formatverktøy", tagline: "Formater, minifiser og valider JSON" },
    nl: { icon: "🧩", name: "JSON Formatter", tagline: "JSON opmaken, minificeren en valideren" },
    it: { icon: "🧩", name: "Formattatore JSON", tagline: "Abbella, minimizza e convalida JSON" },
    ru: { icon: "🧩", name: "JSON форматтер", tagline: "Форматирование и проверка" },
    "ur-pk": { icon: "🧩", name: "JSON فارمیٹر", tagline: "JSON خوبصورت بنائیں، چھوٹا کریں، جانچیں" },
  },
  loremIpsum: {
    en: { icon: "📄", name: "Lorem Ipsum Generator", tagline: "Paragraphs, sentences & words" },
    es: { icon: "📄", name: "Generador Lorem Ipsum", tagline: "Párrafos, frases y palabras" },
    ur: { icon: "📄", name: "Lorem Ipsum Generator", tagline: "Paragraph, jumlay aur alfaz banayen" },
    de: { icon: "📄", name: "Lorem Ipsum Generator", tagline: "Absätze, Sätze & Wörter" },
    fr: { icon: "📄", name: "Générateur Lorem Ipsum", tagline: "Paragraphes, phrases et mots" },
    tr: { icon: "📄", name: "Lorem Ipsum Oluşturucu", tagline: "Paragraf, cümle ve kelime" },
    pt: { icon: "📄", name: "Gerador Lorem Ipsum", tagline: "Parágrafos, frases e palavras" },
    ja: { icon: "📄", name: "Lorem Ipsum生成", tagline: "段落・文・単語数でダミーテキスト" },
    no: { icon: "📄", name: "Lorem Ipsum-generator", tagline: "Avsnitt, setninger og ord" },
    nl: { icon: "📄", name: "Lorem Ipsum Generator", tagline: "Alinea's, zinnen en woorden" },
    it: { icon: "📄", name: "Generatore Lorem Ipsum", tagline: "Paragrafi, frasi e parole" },
    ru: { icon: "📄", name: "Lorem Ipsum", tagline: "Генератор текста-рыбы" },
    "ur-pk": { icon: "📄", name: "لورم اپسم بنانے والا", tagline: "ترتیب کے لیے نمونہ متن فوراً بنائیں" },
  },
  daysBetween: {
    en: { icon: "📅", name: "Days Between Dates", tagline: "Total days, weeks & business days" },
    es: { icon: "📅", name: "Días Entre Fechas", tagline: "Días totales, semanas y días laborables" },
    ur: { icon: "📅", name: "Days Between Dates", tagline: "Kul din, haftay aur business days" },
    de: { icon: "📅", name: "Tage Zwischen Daten", tagline: "Tage gesamt, Wochen & Werktage" },
    fr: { icon: "📅", name: "Jours Entre Dates", tagline: "Jours totaux, semaines et jours ouvrés" },
    tr: { icon: "📅", name: "Tarihler Arası Gün", tagline: "Toplam gün, hafta ve iş günleri" },
    pt: { icon: "📅", name: "Dias Entre Datas", tagline: "Total de dias, semanas e dias úteis" },
    ja: { icon: "📅", name: "日付間の日数", tagline: "総日数・週数・営業日を表示" },
    no: { icon: "📅", name: "Dager Mellom Datoer", tagline: "Dager totalt, uker og virkedager" },
    nl: { icon: "📅", name: "Dagen Tussen Datums", tagline: "Dagen totaal, weken en werkdagen" },
    it: { icon: "📅", name: "Giorni Tra Date", tagline: "Giorni totali, settimane e giorni lavorativi" },
    ru: { icon: "📅", name: "Дни между датами", tagline: "Калькулятор дат онлайн" },
    "ur-pk": { icon: "📅", name: "دن کیلکولیٹر", tagline: "دو تاریخوں کے درمیان دن گنیں" },
  },
  randomNumber: {
    en: { icon: "🎲", name: "Random Number Generator", tagline: "Numbers, coin flip & dice rolls" },
    es: { icon: "🎲", name: "Generador de Números Aleatorios", tagline: "Números, moneda y dados" },
    ur: { icon: "🎲", name: "Random Number Generator", tagline: "Number, sikka aur paansa" },
    de: { icon: "🎲", name: "Zufallszahlengenerator", tagline: "Zahlen, Münzwurf & Würfel" },
    fr: { icon: "🎲", name: "Générateur de Nombres Aléatoires", tagline: "Nombres, pile ou face et dés" },
    tr: { icon: "🎲", name: "Rastgele Sayı Üretici", tagline: "Sayılar, yazı tura ve zar" },
    pt: { icon: "🎲", name: "Gerador de Números Aleatórios", tagline: "Números, cara ou coroa e dados" },
    ja: { icon: "🎲", name: "乱数ジェネレーター", tagline: "数字・コイン・サイコロ" },
    no: { icon: "🎲", name: "Tilfeldig Tallgenerator", tagline: "Tall, myntkast og terning" },
    nl: { icon: "🎲", name: "Willekeurig Getalgenerator", tagline: "Getallen, munt en dobbelstenen" },
    it: { icon: "🎲", name: "Generatore di Numeri Casuali", tagline: "Numeri, moneta e dadi" },
    ru: { icon: "🎲", name: "Случайные числа", tagline: "Генератор чисел онлайн" },
    "ur-pk": { icon: "🎲", name: "بے ترتیب عدد بنانے والا", tagline: "منصفانہ بے ترتیب عدد، سکہ اور پاسہ" },
  },
  imageConverter: {
    en: { icon: "🔁", name: "Image Converter", tagline: "JPG, PNG & WebP, same size" },
    es: { icon: "🔁", name: "Convertidor de Imágenes", tagline: "JPG, PNG y WebP, mismo tamaño" },
    ur: { icon: "🔁", name: "Image Converter", tagline: "JPG, PNG aur WebP, wohi size" },
    de: { icon: "🔁", name: "Bildkonverter", tagline: "JPG, PNG & WebP, gleiche Größe" },
    fr: { icon: "🔁", name: "Convertisseur d'Images", tagline: "JPG, PNG et WebP, même taille" },
    tr: { icon: "🔁", name: "Resim Dönüştürücü", tagline: "JPG, PNG ve WebP, aynı boyut" },
    pt: { icon: "🔁", name: "Conversor de Imagem", tagline: "JPG, PNG e WebP, mesmo tamanho" },
    ja: { icon: "🔁", name: "画像コンバーター", tagline: "JPG・PNG・WebP、サイズそのまま" },
    no: { icon: "🔁", name: "Bildekonverter", tagline: "JPG, PNG og WebP, samme størrelse" },
    nl: { icon: "🔁", name: "Afbeelding Converter", tagline: "JPG, PNG en WebP, zelfde grootte" },
    it: { icon: "🔁", name: "Convertitore Immagini", tagline: "JPG, PNG e WebP, stessa dimensione" },
    ru: { icon: "🔁", name: "Конвертер картинок", tagline: "JPG, PNG и WebP" },
    "ur-pk": { icon: "🔁", name: "تصویر شکل بدلنے والا", tagline: "JPG، PNG اور WebP کے درمیان بدلیں" },
  },
  imageToText: {
    en: { icon: "🔍", name: "Image to Text OCR", tagline: "Extract text from JPG, PNG & WebP" },
    es: { icon: "🔍", name: "Imagen a Texto", tagline: "Extrae texto de JPG, PNG y WebP" },
    ur: { icon: "🔍", name: "Image to Text", tagline: "Tasveer se text nikalen" },
    de: { icon: "🔍", name: "Bild zu Text", tagline: "Text aus JPG, PNG & WebP" },
    fr: { icon: "🔍", name: "Image vers Texte", tagline: "Texte de JPG, PNG et WebP" },
    tr: { icon: "🔍", name: "Resimden Metne", tagline: "JPG, PNG ve WebP'den metin" },
    pt: { icon: "🔍", name: "Imagem para Texto", tagline: "Texto de JPG, PNG e WebP" },
    ja: { icon: "🔍", name: "画像からテキスト", tagline: "JPG・PNG・WebPから文字抽出" },
    no: { icon: "🔍", name: "Bilde til Tekst", tagline: "Tekst fra JPG, PNG og WebP" },
    nl: { icon: "🔍", name: "Afbeelding naar Tekst", tagline: "Tekst uit JPG, PNG en WebP" },
    it: { icon: "🔍", name: "Immagine a Testo", tagline: "Testo da JPG, PNG e WebP" },
    ru: { icon: "🔍", name: "Текст с картинки", tagline: "Распознавание текста OCR" },
    "ur-pk": { icon: "🔍", name: "تصویر سے متن (OCR)", tagline: "تصویر سے قابلِ ترمیم متن نکالیں" },
  },
  pdfSplitter: {
    en: { icon: "✂️", name: "PDF Splitter", tagline: "Extract pages & split ranges" },
    es: { icon: "✂️", name: "Dividir PDF", tagline: "Extrae páginas y rangos" },
    ur: { icon: "✂️", name: "PDF Splitter", tagline: "Safhaat alag karen, range split" },
    de: { icon: "✂️", name: "PDF Teilen", tagline: "Seiten & Bereiche extrahieren" },
    fr: { icon: "✂️", name: "Diviser PDF", tagline: "Extraire pages et plages" },
    tr: { icon: "✂️", name: "PDF Bölme", tagline: "Sayfaları ve aralıkları çıkar" },
    pt: { icon: "✂️", name: "Dividir PDF", tagline: "Extrair páginas e intervalos" },
    ja: { icon: "✂️", name: "PDF分割", tagline: "ページと範囲を抽出" },
    no: { icon: "✂️", name: "Del PDF", tagline: "Hent ut sider og intervaller" },
    nl: { icon: "✂️", name: "PDF Splitsen", tagline: "Pagina's en bereiken uitpakken" },
    it: { icon: "✂️", name: "Dividi PDF", tagline: "Estrai pagine e intervalli" },
    ru: { icon: "✂️", name: "Разделить PDF", tagline: "Страницы из PDF файла" },
    "ur-pk": { icon: "✂️", name: "PDF الگ کرنے والا", tagline: "PDF سے مطلوبہ صفحات نکالیں" },
  },
  usernameGenerator: {
    en: { icon: "@", name: "Username Generator", tagline: "Ideas for games, creators & brands" },
    es: { icon: "@", name: "Generador de Usuarios", tagline: "Ideas para juegos, creadores y marcas" },
    ur: { icon: "@", name: "Username Generator", tagline: "Games, creators aur brands ke ideas" },
    de: { icon: "@", name: "Benutzername Generator", tagline: "Ideen für Spiele, Creator & Marken" },
    fr: { icon: "@", name: "Générateur de Pseudo", tagline: "Idées jeux, créateurs et marques" },
    tr: { icon: "@", name: "Kullanıcı Adı Oluşturucu", tagline: "Oyun, üretici ve marka fikirleri" },
    pt: { icon: "@", name: "Gerador de Usuário", tagline: "Ideias para jogos, criadores e marcas" },
    ja: { icon: "@", name: "ユーザー名生成", tagline: "ゲーム・クリエイター・ブランド向け" },
    no: { icon: "@", name: "Brukernavn Generator", tagline: "Ideer for spill, skapere og merker" },
    nl: { icon: "@", name: "Gebruikersnaam Generator", tagline: "Ideeën voor games, makers en merken" },
    it: { icon: "@", name: "Generatore Username", tagline: "Idee per giochi, creator e marchi" },
    ru: { icon: "@", name: "Генератор ников", tagline: "Идеи никнеймов онлайн" },
    "ur-pk": { icon: "@", name: "صارف نام بنانے والا", tagline: "20 صاف صارف نام خیالات حاصل کریں" },
  },
  onlineNotepad: {
    en: { icon: "📝", name: "Online Notepad", tagline: "Type now — it saves itself in this browser" },
    es: { icon: "📝", name: "Bloc de notas online", tagline: "Escribe ahora: se guarda solo en tu navegador" },
    ur: { icon: "📝", name: "Online Notepad", tagline: "Abhi likho — is browser mein khud save hoga" },
    de: { icon: "📝", name: "Online-Notizblock", tagline: "Jetzt tippen — speichert sich in diesem Browser" },
    fr: { icon: "📝", name: "Bloc-notes en ligne", tagline: "Écrivez : tout se sauvegarde dans ce navigateur" },
    tr: { icon: "📝", name: "Online Not Defteri", tagline: "Hemen yaz — bu tarayıcıda kendiliğinden kaydedilir" },
    pt: { icon: "📝", name: "Bloco de notas online", tagline: "Digite agora — salva sozinho neste navegador" },
    ja: { icon: "📝", name: "オンラインメモ帳", tagline: "今すぐ入力 — このブラウザに自動保存" },
    no: { icon: "📝", name: "Notatblokk på nett", tagline: "Skriv no — lagrar seg sjølv i nettlesaren" },
    nl: { icon: "📝", name: "Online kladblok", tagline: "Typ direct — slaat zichzelf op in je browser" },
    it: { icon: "📝", name: "Blocco note online", tagline: "Scrivi ora — si salva da solo in questo browser" },
    ru: { icon: "📝", name: "Блокнот онлайн", tagline: "Заметки в браузере" },
    "ur-pk": { icon: "📝", name: "آن لائن نوٹ پیڈ", tagline: "کھولتے ہی لکھیں، خود محفوظ ہو جائے" },
  },
  onlineTeleprompter: {
    en: { icon: "🎬", name: "Online Teleprompter", tagline: "Scrolling script, mirror & countdown" },
    es: { icon: "🎬", name: "Teleprompter Online", tagline: "Guion desplazable, espejo y cuenta atrás" },
    ur: { icon: "🎬", name: "Online Teleprompter", tagline: "Scroll script, mirror aur countdown" },
    de: { icon: "🎬", name: "Online Teleprompter", tagline: "Lauftext, Spiegel & Countdown" },
    fr: { icon: "🎬", name: "Téléprompteur", tagline: "Texte défilant, miroir et compte à rebours" },
    tr: { icon: "🎬", name: "Online Teleprompter", tagline: "Kayan metin, ayna ve geri sayım" },
    pt: { icon: "🎬", name: "Teleprompter Online", tagline: "Roteiro rolante, espelho e contagem" },
    ja: { icon: "🎬", name: "テレプロンプター", tagline: "流れる原稿・ミラー・カウントダウン" },
    no: { icon: "🎬", name: "Teleprompter", tagline: "Rullende tekst, speil og nedtelling" },
    nl: { icon: "🎬", name: "Teleprompter", tagline: "Scrollende tekst, spiegel en aftellen" },
    it: { icon: "🎬", name: "Teleprompter", tagline: "Testo scorrevole, specchio e conto" },
    ru: { icon: "🎬", name: "Телесуфлёр", tagline: "Суфлёр для записи видео" },
    "ur-pk": { icon: "🎬", name: "آن لائن ٹیلی پرامپٹر", tagline: "اسکرپٹ پڑھیں جبکہ وہ سکون سے گزرے" },
  },
  timestampConverter: {
    en: { icon: "🕐", name: "Timestamp Converter", tagline: "Epoch, UTC & local — unit stated" },
    es: { icon: "🕐", name: "Convertidor Timestamp", tagline: "Epoch, UTC y local, unidad clara" },
    ur: { icon: "🕐", name: "Timestamp Converter", tagline: "Epoch, UTC aur local, unit wazeh" },
    de: { icon: "🕐", name: "Timestamp-Konverter", tagline: "Epoch, UTC & lokal, Einheit klar" },
    fr: { icon: "🕐", name: "Convertisseur Timestamp", tagline: "Epoch, UTC et local, unité claire" },
    tr: { icon: "🕐", name: "Zaman Damgası Çevirici", tagline: "Epoch, UTC ve yerel, birim açık" },
    pt: { icon: "🕐", name: "Conversor Timestamp", tagline: "Epoch, UTC e local, unidade clara" },
    ja: { icon: "🕐", name: "タイムスタンプ変換", tagline: "エポック、UTCとローカル、単位明示" },
    no: { icon: "🕐", name: "Tidsstempel-omregner", tagline: "Epoch, UTC og lokal, enhet vist" },
    nl: { icon: "🕐", name: "Timestamp Converter", tagline: "Epoch, UTC & lokaal, eenheid vermeld" },
    it: { icon: "🕐", name: "Convertitore Timestamp", tagline: "Epoch, UTC e locale, unità chiara" },
    ru: { icon: "🕐", name: "Конвертер времени", tagline: "Unix timestamp в дату" },
    "ur-pk": { icon: "🕐", name: "ٹائم اسٹیمپ کنورٹر", tagline: "یونکس وقت کو تاریخ میں اور واپس بدلیں" },
  },
  utmLinkBuilder: {
    en: { icon: "📣", name: "UTM Link Builder", tagline: "Source, medium & campaign — tagged right" },
    es: { icon: "📣", name: "Constructor UTM", tagline: "Fuente, medio y campaña, bien etiquetados" },
    ur: { icon: "📣", name: "UTM Link Builder", tagline: "Source, medium aur campaign — sahi tag" },
    de: { icon: "📣", name: "UTM Link Builder", tagline: "Source, Medium & Kampagne richtig markiert" },
    fr: { icon: "📣", name: "Générateur UTM", tagline: "Source, canal et campagne bien étiquetés" },
    tr: { icon: "📣", name: "UTM Bağlantı Oluşturucu", tagline: "Kaynak, aracı ve kampanya doğru etiketli" },
    pt: { icon: "📣", name: "Construtor UTM", tagline: "Origem, mídia e campanha bem marcadas" },
    ja: { icon: "📣", name: "UTMリンクビルダー", tagline: "ソース・メディア・キャンペーンを正しく" },
    no: { icon: "📣", name: "UTM-lenkebygger", tagline: "Kilde, medium og kampanje merket riktig" },
    nl: { icon: "📣", name: "UTM-linkbouwer", tagline: "Bron, medium en campagne goed getagd" },
    it: { icon: "📣", name: "Generatore UTM", tagline: "Fonte, mezzo e campagna etichettati bene" },
    ru: { icon: "📣", name: "UTM метки", tagline: "Ссылки для рекламы" },
    "ur-pk": { icon: "📣", name: "UTM لنک بنانے والا", tagline: "ماخذ، ذریعہ اور مہم کے ساتھ لنک ٹیگ کریں" },
  },
  metaChecker: {
    en: { icon: "🔍", name: "Meta Length Checker", tagline: "Characters, pixels & SERP preview" },
    es: { icon: "🔍", name: "Longitud Meta", tagline: "Caracteres, píxeles y vista previa SERP" },
    ur: { icon: "🔍", name: "Meta Length Checker", tagline: "Characters, pixels aur SERP preview" },
    de: { icon: "🔍", name: "Meta-Längenprüfer", tagline: "Zeichen, Pixel & SERP-Vorschau" },
    fr: { icon: "🔍", name: "Longueur Meta", tagline: "Caractères, pixels et aperçu SERP" },
    tr: { icon: "🔍", name: "Meta Uzunluk Denetimi", tagline: "Karakter, piksel ve SERP önizleme" },
    pt: { icon: "🔍", name: "Comprimento Meta", tagline: "Caracteres, pixels e prévia SERP" },
    ja: { icon: "🔍", name: "メタ長さチェッカー", tagline: "文字数・ピクセル・SERPプレビュー" },
    no: { icon: "🔍", name: "Meta-lengdesjekk", tagline: "Tegn, piksler og SERP-visning" },
    nl: { icon: "🔍", name: "Meta Lengtechecker", tagline: "Tekens, pixels & SERP-voorbeeld" },
    it: { icon: "🔍", name: "Lunghezza Meta", tagline: "Caratteri, pixel e anteprima SERP" },
    ru: { icon: "🔍", name: "Проверка мета-тегов", tagline: "Title и description" },
    "ur-pk": { icon: "🔍", name: "میٹا جانچنے والا", tagline: "عنوان و تفصیل کی لمبائی اور جھلک جانچیں" },
  },
  urlEncoder: {
    en: { icon: "🔗", name: "URL Encoder / Decoder", tagline: "Full links or single values — encoded right" },
    es: { icon: "🔗", name: "Codificador de URL", tagline: "Enlaces completos o valores sueltos, bien codificados" },
    ur: { icon: "🔗", name: "URL Encoder Decoder", tagline: "Poora link ya ek value — sahi encode" },
    de: { icon: "🔗", name: "URL-Kodierer", tagline: "Ganze Links oder Einzelwerte korrekt kodiert" },
    fr: { icon: "🔗", name: "Encodeur d'URL", tagline: "Liens entiers ou valeurs seules, bien encodés" },
    tr: { icon: "🔗", name: "URL Kodlayıcı", tagline: "Tam bağlantı veya tek değer, doğru kodlama" },
    pt: { icon: "🔗", name: "Codificador de URL", tagline: "Links completos ou valores únicos, bem codificados" },
    ja: { icon: "🔗", name: "URLエンコーダー", tagline: "URL全体か値1つか、正しく変換" },
    no: { icon: "🔗", name: "URL-koder", tagline: "Hele lenker eller enkelverdier, riktig kodet" },
    nl: { icon: "🔗", name: "URL-encoder", tagline: "Hele links of losse waarden, goed gecodeerd" },
    it: { icon: "🔗", name: "Codificatore URL", tagline: "Link interi o singoli valori, codifica giusta" },
    ru: { icon: "🔗", name: "Кодирование URL", tagline: "Encode и decode онлайн" },
    "ur-pk": { icon: "🔗", name: "URL انکوڈر / ڈیکوڈر", tagline: "URL یا ایک قدر کو انکوڈ ڈیکوڈ کریں" },
  },
  regexTester: {
    en: { icon: "🔎", name: "Regex Tester", tagline: "Matches, groups & replace — live" },
    es: { icon: "🔎", name: "Probador de Regex", tagline: "Coincidencias, grupos y reemplazo en vivo" },
    ur: { icon: "🔎", name: "Regex Tester", tagline: "Matches, groups aur replace — live" },
    de: { icon: "🔎", name: "Regex Tester", tagline: "Treffer, Gruppen & Ersetzen live" },
    fr: { icon: "🔎", name: "Testeur Regex", tagline: "Correspondances, groupes, remplacement" },
    tr: { icon: "🔎", name: "Regex Test Aracı", tagline: "Eşleşmeler, gruplar ve değiştirme canlı" },
    pt: { icon: "🔎", name: "Testador de Regex", tagline: "Correspondências, grupos e substituição" },
    ja: { icon: "🔎", name: "正規表現テスター", tagline: "マッチ・グループ・置換をライブ確認" },
    no: { icon: "🔎", name: "Regex-tester", tagline: "Treff, grupper og erstatning direkte" },
    nl: { icon: "🔎", name: "Regex Tester", tagline: "Matches, groepen en vervangen live" },
    it: { icon: "🔎", name: "Tester Regex", tagline: "Corrispondenze, gruppi e sostituzione" },
    ru: { icon: "🔎", name: "Тестер regex", tagline: "Регулярные выражения" },
    "ur-pk": { icon: "🔎", name: "ریگ ایکس جانچنے والا", tagline: "نمونہ لائیو جانچیں، مماثلتیں دیکھیں" },
  },
  jsonToCsv: {
    en: { icon: "📊", name: "JSON to CSV Converter", tagline: "Flatten, preview & safe export" },
    es: { icon: "📊", name: "Convertidor JSON a CSV", tagline: "Aplana, previsualiza y exporta seguro" },
    ur: { icon: "📊", name: "JSON to CSV Converter", tagline: "Flatten, preview aur safe export" },
    de: { icon: "📊", name: "JSON-zu-CSV-Konverter", tagline: "Abflachen, Vorschau & sicherer Export" },
    fr: { icon: "📊", name: "Convertisseur JSON en CSV", tagline: "Aplatir, aperçu et export sûr" },
    tr: { icon: "📊", name: "JSON-CSV Dönüştürücü", tagline: "Düzleştir, önizle, güvenli dışa aktar" },
    pt: { icon: "📊", name: "Conversor JSON para CSV", tagline: "Achatar, pré-visualizar, exportar seguro" },
    ja: { icon: "📊", name: "JSON CSV変換", tagline: "平坦化・プレビュー・安全な出力" },
    no: { icon: "📊", name: "JSON til CSV-omformer", tagline: "Flat ut, forhåndsvis, trygg eksport" },
    nl: { icon: "📊", name: "JSON naar CSV-converter", tagline: "Afplatten, voorbeeld, veilige export" },
    it: { icon: "📊", name: "Convertitore JSON in CSV", tagline: "Appiattisci, anteprima, export sicuro" },
    ru: { icon: "📊", name: "JSON в CSV", tagline: "Конвертер таблиц онлайн" },
    "ur-pk": { icon: "📊", name: "JSON سے CSV کنورٹر", tagline: "JSON کو صاف اسپریڈ شیٹ CSV بنائیں" },
  },
  uuidGenerator: {
    en: { icon: "🆔", name: "UUID Generator", tagline: "Random v4 IDs, bulk & one-tap copy" },
    es: { icon: "🆔", name: "Generador UUID", tagline: "UUID v4 en lote y copia con un toque" },
    ur: { icon: "🆔", name: "UUID Generator", tagline: "Bulk UUID v4, ek tap mein copy" },
    de: { icon: "🆔", name: "UUID Generator", tagline: "UUID v4 im Stapel, Kopie per Tippen" },
    fr: { icon: "🆔", name: "Générateur UUID", tagline: "UUID v4 en lot, copie en un geste" },
    tr: { icon: "🆔", name: "UUID Oluşturucu", tagline: "Toplu UUID v4, tek dokunuşla kopyala" },
    pt: { icon: "🆔", name: "Gerador de UUID", tagline: "UUID v4 em lote, copie com um toque" },
    ja: { icon: "🆔", name: "UUID生成", tagline: "UUID v4を一括作成、ワンタップコピー" },
    no: { icon: "🆔", name: "UUID-generator", tagline: "UUID v4 i bulk, kopi med ett trykk" },
    nl: { icon: "🆔", name: "UUID Generator", tagline: "UUID v4 in bulk, kopiëren met één tik" },
    it: { icon: "🆔", name: "Generatore UUID", tagline: "UUID v4 in blocco, copia con un tocco" },
    ru: { icon: "🆔", name: "Генератор UUID", tagline: "GUID в один клик" },
    "ur-pk": { icon: "🆔", name: "UUID بنانے والا", tagline: "UUID v4 فوراً بنائیں، ایک یا سو" },
  },
  unitConverter: {
    en: { icon: "📏", name: "Unit Converter", tagline: "Length, weight, temperature & more — no currency" },
    es: { icon: "📏", name: "Conversor de Unidades", tagline: "Longitud, peso, temperatura y más" },
    ur: { icon: "📏", name: "Unit Converter", tagline: "Lambai, wazan, temperature — currency nahi" },
    de: { icon: "📏", name: "Einheitenrechner", tagline: "Länge, Gewicht, Temperatur & mehr" },
    fr: { icon: "📏", name: "Convertisseur d'Unités", tagline: "Longueur, poids, température et plus" },
    tr: { icon: "📏", name: "Birim Dönüştürücü", tagline: "Uzunluk, ağırlık, sıcaklık ve daha fazlası" },
    pt: { icon: "📏", name: "Conversor de Unidades", tagline: "Comprimento, peso, temperatura e mais" },
    ja: { icon: "📏", name: "単位変換", tagline: "長さ・重さ・温度などを変換" },
    no: { icon: "📏", name: "Enhetsomregner", tagline: "Lengde, vekt, temperatur og mer" },
    nl: { icon: "📏", name: "Eenheden Omrekenen", tagline: "Lengte, gewicht, temperatuur en meer" },
    it: { icon: "📏", name: "Convertitore di Unità", tagline: "Lunghezza, peso, temperatura e altro" },
    ru: { icon: "📏", name: "Конвертер единиц", tagline: "Длина, вес, температура" },
    "ur-pk": { icon: "📏", name: "یونٹ کنورٹر", tagline: "لمبائی، وزن، درجہ حرارت اور مزید بدلیں" },
  },
  voiceRecorder: {
    en: { icon: "🎙️", name: "Online Voice Recorder", tagline: "Record, pause & download — no upload" },
    es: { icon: "🎙️", name: "Grabadora de Voz Online", tagline: "Graba, pausa y descarga, sin subir nada" },
    ur: { icon: "🎙️", name: "Online Voice Recorder", tagline: "Record karein, pause karein, download karein — upload nahi" },
    de: { icon: "🎙️", name: "Online Sprachrekorder", tagline: "Aufnehmen, pausieren & herunterladen" },
    fr: { icon: "🎙️", name: "Enregistreur Vocal en Ligne", tagline: "Enregistrez, pausez, téléchargez" },
    tr: { icon: "🎙️", name: "Online Ses Kaydedici", tagline: "Kaydet, duraklat, indir — yükleme yok" },
    pt: { icon: "🎙️", name: "Gravador de Voz Online", tagline: "Grave, pause e baixe — sem upload" },
    ja: { icon: "🎙️", name: "オンラインボイスレコーダー", tagline: "録音・一時停止・ダウンロード" },
    no: { icon: "🎙️", name: "Taleopptaker på Nett", tagline: "Ta opp, pause og last ned" },
    nl: { icon: "🎙️", name: "Online Spraakrecorder", tagline: "Opnemen, pauzeren & downloaden" },
    it: { icon: "🎙️", name: "Registratore Vocale Online", tagline: "Registra, metti in pausa e scarica" },
    ru: { icon: "🎙️", name: "Диктофон онлайн", tagline: "Запись голоса в браузере" },
    "ur-pk": { icon: "🎙️", name: "آن لائن آواز ریکارڈر", tagline: "براؤزر میں آواز ریکارڈ کریں، ڈاؤن لوڈ کریں" },
  },
  morseCodeTranslator: {
    en: { icon: "📡", name: "Morse Code Translator", tagline: "Dots, dashes, sound & flash" },
    es: { icon: "📡", name: "Traductor de Código Morse", tagline: "Puntos, rayas, sonido y luz" },
    ur: { icon: "📡", name: "Morse Code Translator", tagline: "Dots, dashes, awaz aur flash" },
    de: { icon: "📡", name: "Morsecode Übersetzer", tagline: "Punkte, Striche, Ton & Licht" },
    fr: { icon: "📡", name: "Traducteur Code Morse", tagline: "Points, traits, son et flash" },
    tr: { icon: "📡", name: "Mors Kodu Çevirici", tagline: "Nokta, çizgi, ses ve ışık" },
    pt: { icon: "📡", name: "Tradutor de Código Morse", tagline: "Pontos, traços, som e luz" },
    ja: { icon: "📡", name: "モールス信号変換", tagline: "トンツー・音・フラッシュ" },
    no: { icon: "📡", name: "Morsekode Oversetter", tagline: "Prikker, streker, lyd og lys" },
    nl: { icon: "📡", name: "Morsecode Vertaler", tagline: "Punten, strepen, geluid & licht" },
    it: { icon: "📡", name: "Traduttore Codice Morse", tagline: "Punti, linee, suono e luce" },
    ru: { icon: "📡", name: "Азбука Морзе", tagline: "Переводчик туда и обратно" },
    "ur-pk": { icon: "📡", name: "مورس کوڈ مترجم", tagline: "متن کو نقطوں لکیروں میں اور واپس بدلیں" },
  },
  imageResizer: {
    en: { icon: "🖼️", name: "Image Resizer", tagline: "Exact pixels, crop & social presets" },
    es: { icon: "🖼️", name: "Redimensionar Imagen", tagline: "Píxeles exactos, recorte y preajustes" },
    ur: { icon: "🖼️", name: "Image Resizer", tagline: "Saheeh size, crop aur presets" },
    de: { icon: "🖼️", name: "Bild Skalieren", tagline: "Exakte Pixel, Zuschnitt & Presets" },
    fr: { icon: "🖼️", name: "Redimensionner", tagline: "Pixels exacts, recadrage et préréglages" },
    tr: { icon: "🖼️", name: "Resim Boyutlandır", tagline: "Tam piksel, kırpma ve hazır ayarlar" },
    pt: { icon: "🖼️", name: "Redimensionar", tagline: "Pixels exatos, recorte e predefinições" },
    ja: { icon: "🖼️", name: "画像リサイズ", tagline: "正確なピクセル・切り抜き・プリセット" },
    no: { icon: "🖼️", name: "Bildestørrelse", tagline: "Nøyaktige piksler, beskjæring og forvalg" },
    nl: { icon: "🖼️", name: "Formaat Wijzigen", tagline: "Exacte pixels, bijsnijden en presets" },
    it: { icon: "🖼️", name: "Ridimensiona", tagline: "Pixel esatti, ritaglio e preset" },
    ru: { icon: "🖼️", name: "Размер фото", tagline: "Изменить размер картинки" },
    "ur-pk": { icon: "🖼️", name: "تصویر سائز بدلنے والا", tagline: "تصویر کو درست سائز میں بدلیں اور تراشیں" },
  },
  invoiceGenerator: {
    en: { icon: "🧾", name: "Invoice Generator", tagline: "Make a clean invoice and print or save PDF" },
    es: { icon: "🧾", name: "Generador de Facturas", tagline: "Crea una factura limpia e imprime o guarda PDF" },
    ur: { icon: "🧾", name: "Invoice Generator", tagline: "Saaf invoice banayen, print ya PDF save karen" },
    de: { icon: "🧾", name: "Rechnung Generator", tagline: "Saubere Rechnung erstellen, drucken oder PDF" },
    fr: { icon: "🧾", name: "Générateur de Factures", tagline: "Créez une facture nette, imprimez ou PDF" },
    tr: { icon: "🧾", name: "Fatura Oluşturucu", tagline: "Temiz fatura yapın, yazdırın veya PDF kaydedin" },
    pt: { icon: "🧾", name: "Gerador de Faturas", tagline: "Faça uma fatura limpa, imprima ou salve PDF" },
    ja: { icon: "🧾", name: "請求書ジェネレーター", tagline: "きれいな請求書を作成し印刷・PDF保存" },
    no: { icon: "🧾", name: "Fakturagenerator", tagline: "Lag en ryddig faktura, skriv ut eller PDF" },
    nl: { icon: "🧾", name: "Factuurgenerator", tagline: "Maak een nette factuur, druk af of PDF" },
    it: { icon: "🧾", name: "Generatore di Fatture", tagline: "Crea una fattura pulita, stampa o PDF" },
    ru: { icon: "🧾", name: "Счета онлайн", tagline: "Генератор счетов на оплату" },
    "ur-pk": { icon: "🧾", name: "رسید بنانے والا", tagline: "منٹوں میں صاف رسید بنائیں اور چھاپیں" },
  },
  onlineTimer: {
    en: { icon: "⏱️", name: "Online Timer & Stopwatch", tagline: "Countdown, laps & big readable digits" },
    es: { icon: "⏱️", name: "Temporizador y Cronómetro", tagline: "Cuenta atrás, vueltas y dígitos grandes" },
    ur: { icon: "⏱️", name: "Online Timer aur Stopwatch", tagline: "Countdown, laps aur barre digits" },
    de: { icon: "⏱️", name: "Online-Timer & Stoppuhr", tagline: "Countdown, Runden & große Ziffern" },
    fr: { icon: "⏱️", name: "Minuteur et Chronomètre", tagline: "Compte à rebours, tours et grands chiffres" },
    tr: { icon: "⏱️", name: "Zamanlayıcı ve Kronometre", tagline: "Geri sayım, turlar ve büyük rakamlar" },
    pt: { icon: "⏱️", name: "Temporizador e Cronômetro", tagline: "Contagem, voltas e dígitos grandes" },
    ja: { icon: "⏱️", name: "タイマー＆ストップウォッチ", tagline: "カウントダウン・ラップ・大きな数字" },
    no: { icon: "⏱️", name: "Tidtaker og Stoppeklokke", tagline: "Nedtelling, runder og store sifre" },
    nl: { icon: "⏱️", name: "Timer en Stopwatch", tagline: "Aftellen, ronden en grote cijfers" },
    it: { icon: "⏱️", name: "Timer e Cronometro", tagline: "Conto alla rovescia, giri e cifre grandi" },
    ru: { icon: "⏱️", name: "Таймер онлайн", tagline: "Обратный отсчёт со звуком" },
    "ur-pk": { icon: "⏱️", name: "آن لائن ٹائمر", tagline: "الٹی گنتی اور اسٹاپ واچ ایک ہی جگہ" },
  },
  slugGenerator: {
    en: { icon: "🔗", name: "Slug Generator", tagline: "Titles into clean URL slugs" },
    es: { icon: "🔗", name: "Generador de Slugs", tagline: "Títulos a slugs limpios" },
    ur: { icon: "🔗", name: "Slug Generator", tagline: "Title se saaf URL slug" },
    de: { icon: "🔗", name: "Slug-Generator", tagline: "Titel in saubere URL-Slugs" },
    fr: { icon: "🔗", name: "Générateur de Slug", tagline: "Des titres en slugs propres" },
    tr: { icon: "🔗", name: "Slug Oluşturucu", tagline: "Başlıktan temiz URL slugı" },
    pt: { icon: "🔗", name: "Gerador de Slug", tagline: "Títulos em slugs limpos" },
    ja: { icon: "🔗", name: "スラッグ生成", tagline: "タイトルをきれいなURLに" },
    no: { icon: "🔗", name: "Slug-generator", tagline: "Titler til rene URL-slugger" },
    nl: { icon: "🔗", name: "Slug Generator", tagline: "Titels naar schone URL-slugs" },
    it: { icon: "🔗", name: "Generatore di Slug", tagline: "Titoli in slug puliti" },
    ru: { icon: "🔗", name: "Генератор слага", tagline: "ЧПУ и транслит в URL" },
    "ur-pk": { icon: "🔗", name: "سلگ بنانے والا", tagline: "عنوان کو صاف URL سلگ بنائیں" },
  },
  textRepeater: {
    en: { icon: "🔁", name: "Text Repeater", tagline: "Repeat any text up to 1,000 times" },
    es: { icon: "🔁", name: "Repetidor de Texto", tagline: "Repite cualquier texto hasta 1.000 veces" },
    ur: { icon: "🔁", name: "Text Repeater", tagline: "Koi bhi text 1,000 dafa tak repeat karein" },
    de: { icon: "🔁", name: "Text-Wiederholer", tagline: "Text bis zu 1.000-mal wiederholen" },
    fr: { icon: "🔁", name: "Répéteur de Texte", tagline: "Répétez un texte jusqu'à 1 000 fois" },
    tr: { icon: "🔁", name: "Metin Tekrarlayıcı", tagline: "Metni 1000 kereye kadar tekrarlayın" },
    pt: { icon: "🔁", name: "Repetidor de Texto", tagline: "Repita qualquer texto até 1.000 vezes" },
    ja: { icon: "🔁", name: "テキストリピーター", tagline: "テキストを最大1,000回繰り返し" },
    no: { icon: "🔁", name: "Tekstgjentaker", tagline: "Gjenta tekst opptil 1 000 ganger" },
    nl: { icon: "🔁", name: "Tekstherhaler", tagline: "Herhaal tekst tot 1.000 keer" },
    it: { icon: "🔁", name: "Ripetitore di Testo", tagline: "Ripeti il testo fino a 1.000 volte" },
    ru: { icon: "🔁", name: "Повторитель текста", tagline: "Повторить текст много раз" },
    "ur-pk": { icon: "🔁", name: "متن دہرانے والا", tagline: "کوئی متن 1,000 بار تک دہرائیں" },
  },
  cvBuilder: {
    en: { icon: "💼", name: "CV Builder", tagline: "Make a professional CV in minutes" },
    es: { icon: "💼", name: "Creador de CV", tagline: "Crea un currículum profesional en minutos" },
    ur: { icon: "💼", name: "CV Builder", tagline: "Minutes mein professional CV banayen" },
    de: { icon: "💼", name: "Lebenslauf-Ersteller", tagline: "In Minuten zum professionellen Lebenslauf" },
    fr: { icon: "💼", name: "Créateur de CV", tagline: "Un CV professionnel en quelques minutes" },
    tr: { icon: "💼", name: "CV Oluşturucu", tagline: "Dakikalar içinde profesyonel CV" },
    pt: { icon: "💼", name: "Criador de Currículo", tagline: "Um currículo profissional em minutos" },
    ja: { icon: "💼", name: "CV作成", tagline: "数分でプロフェッショナルなCVを" },
    no: { icon: "💼", name: "CV-Bygger", tagline: "Profesjonell CV på minutter" },
    nl: { icon: "💼", name: "CV-Maker", tagline: "In minuten een professioneel CV" },
    it: { icon: "💼", name: "Creatore di CV", tagline: "Un CV professionale in pochi minuti" },
    ru: { icon: "💼", name: "Конструктор резюме", tagline: "Резюме онлайн бесплатно" },
    "ur-pk": { icon: "💼", name: "CV بنانے والا", tagline: "صاف پیشہ ورانہ CV بنائیں اور چھاپیں" },
  },
  imageCompressor: {
    en: { icon: "🖼️", name: "Image Compressor", tagline: "Reduce image file size in your browser" },
    es: { icon: "🖼️", name: "Compresor de Imágenes", tagline: "Reduce el tamaño de la imagen en tu navegador" },
    ur: { icon: "🖼️", name: "Image Compressor", tagline: "Browser mein tasveer ka size kam karen" },
    de: { icon: "🖼️", name: "Bildkompressor", tagline: "Bilddateigröße im Browser reduzieren" },
    fr: { icon: "🖼️", name: "Compresseur d'Image", tagline: "Réduisez la taille des images dans votre navigateur" },
    tr: { icon: "🖼️", name: "Resim Sıkıştırıcı", tagline: "Tarayıcıda resim dosya boyutunu küçültün" },
    pt: { icon: "🖼️", name: "Compressor de Imagem", tagline: "Reduza o tamanho da imagem no navegador" },
    ja: { icon: "🖼️", name: "画像圧縮ツール", tagline: "ブラウザで画像容量を削減" },
    no: { icon: "🖼️", name: "Bildekompressor", tagline: "Reduser bildefilstørrelsen i nettleseren" },
    nl: { icon: "🖼️", name: "Afbeeldingcompressor", tagline: "Verklein afbeeldingsbestanden in je browser" },
    it: { icon: "🖼️", name: "Compressore Immagini", tagline: "Riduci la dimensione delle immagini nel browser" },
    ru: { icon: "🖼️", name: "Сжать фото", tagline: "Уменьшить размер картинки" },
    "ur-pk": { icon: "🖼️", name: "تصویر سائز گھٹانے والا", tagline: "تصاویر کا سائز کم کریں، معیار برقرار" },
  },
  pdfTools: {
    en: { icon: "📕", name: "PDF Tools", tagline: "Merge PDFs & turn images into PDF" },
    es: { icon: "📕", name: "Herramientas PDF", tagline: "Une PDFs y convierte imágenes" },
    ur: { icon: "📕", name: "PDF Tools", tagline: "PDF joren aur tasveer se PDF banayen" },
    de: { icon: "📕", name: "PDF-Tools", tagline: "PDFs zusammenführen & Bilder umwandeln" },
    fr: { icon: "📕", name: "Outils PDF", tagline: "Fusionnez PDFs et convertissez images" },
    tr: { icon: "📕", name: "PDF Araçları", tagline: "PDF birleştirin, resimden PDF yapın" },
    pt: { icon: "📕", name: "Ferramentas PDF", tagline: "Junte PDFs e converta imagens" },
    ja: { icon: "📕", name: "PDFツール", tagline: "PDF結合・画像からPDF作成" },
    no: { icon: "📕", name: "PDF-Verktøy", tagline: "Slå sammen PDF og lag PDF av bilder" },
    nl: { icon: "📕", name: "PDF-Tools", tagline: "Voeg PDFs samen, maak PDF van foto's" },
    it: { icon: "📕", name: "Strumenti PDF", tagline: "Unisci PDF e crea PDF da immagini" },
    ru: { icon: "📕", name: "PDF инструменты", tagline: "Объединить и разделить PDF" },
    "ur-pk": { icon: "📕", name: "PDF ٹولز", tagline: "PDF جوڑیں اور تصویریں PDF بنائیں" },
  },
  media: {
    en: { icon: "🎬", name: "Video Studio", tagline: "Edit media you have permission to use" },
    es: { icon: "🎬", name: "Estudio de Video", tagline: "Edita videos e imágenes con permiso de uso" },
    ur: { icon: "🎬", name: "Video Studio", tagline: "Sirf ijazat wali media edit karein" },
    de: { icon: "🎬", name: "Video-Studio", tagline: "Videos und Bilder mit Nutzungsrecht bearbeiten" },
    fr: { icon: "🎬", name: "Studio Vidéo", tagline: "Modifiez des vidéos et images que vous avez le droit d’utiliser" },
    tr: { icon: "🎬", name: "Video Stüdyosu", tagline: "Kullanma izniniz olan video ve resimleri düzenleyin" },
    pt: { icon: "🎬", name: "Estúdio de Vídeo", tagline: "Edite vídeos e imagens que você tem permissão para usar" },
    ja: { icon: "🎬", name: "ビデオスタジオ", tagline: "使用許可のある動画と画像を編集" },
    no: { icon: "🎬", name: "Videostudio", tagline: "Rediger videoer og bilder du har lov til å bruke" },
    nl: { icon: "🎬", name: "Videostudio", tagline: "Bewerk video's en afbeeldingen die je mag gebruiken" },
    it: { icon: "🎬", name: "Studio Video", tagline: "Modifica video e immagini che hai il diritto di usare" },
    ru: { icon: "🎬", name: "Видео инструменты", tagline: "Инструменты для видео" },
    "ur-pk": { icon: "🎬", name: "میڈیا ٹولز", tagline: "ویڈیو و تصویر کے تخلیقی اوزار" },
  },
  seo: {
    en: { icon: "📈", name: "SEO & Hashtags", tagline: "Generate title, keyword & hashtag ideas" },
    es: { icon: "📈", name: "SEO y Hashtags", tagline: "Genera títulos, keywords y hashtags" },
    ur: { icon: "📈", name: "SEO aur Hashtags", tagline: "Title, keywords aur hashtags banayen" },
    de: { icon: "📈", name: "SEO & Hashtags", tagline: "Titel, Keywords & Hashtags generieren" },
    fr: { icon: "📈", name: "SEO et Hashtags", tagline: "Générez titres, mots-clés et hashtags" },
    tr: { icon: "📈", name: "SEO ve Hashtagler", tagline: "Başlık, anahtar kelime oluşturun" },
    pt: { icon: "📈", name: "SEO e Hashtags", tagline: "Gere títulos e hashtags" },
    ja: { icon: "📈", name: "SEO＆ハッシュタグ", tagline: "タイトルとハッシュタグを生成" },
    no: { icon: "📈", name: "SEO og Hashtagger", tagline: "Generer titler og hashtags" },
    nl: { icon: "📈", name: "SEO & Hashtags", tagline: "Genereer titels en hashtags" },
    it: { icon: "📈", name: "SEO e Hashtag", tagline: "Genera titoli e hashtag" },
    ru: { icon: "📈", name: "SEO инструменты", tagline: "Заголовки и мета-описания" },
    "ur-pk": { icon: "📈", name: "SEO مددگار", tagline: "میٹا اور ہیش ٹیگ خیالات بنائیں" },
  },
  cleaner: {
    en: { icon: "🧹", name: "Cliché Cleaner", tagline: "Remove AI buzzwords & robotic phrases" },
    es: { icon: "🧹", name: "Limpiador de Clichés", tagline: "Elimina frases robóticas de IA" },
    ur: { icon: "🧹", name: "Cliché Cleaner", tagline: "AI wale ghise pite lafz hatayen" },
    de: { icon: "🧹", name: "Klischee-Entferner", tagline: "KI-Floskeln entfernen" },
    fr: { icon: "🧹", name: "Nettoyeur de Clichés", tagline: "Supprimez les phrases robotiques" },
    tr: { icon: "🧹", name: "Klişe Temizleyici", tagline: "Yapay ifadeleri temizleyin" },
    pt: { icon: "🧹", name: "Limpador de Clichês", tagline: "Remova frases robóticas" },
    ja: { icon: "🧹", name: "クリシェ除去", tagline: "AIっぽい表現を除去" },
    no: { icon: "🧹", name: "Klisjéfjerner", tagline: "Fjern AI-klisjeer" },
    nl: { icon: "🧹", name: "Clichéverwijderaar", tagline: "Verwijder AI-clichés" },
    it: { icon: "🧹", name: "Pulitore di Cliché", tagline: "Rimuovi frasi robotiche" },
    ru: { icon: "🧹", name: "Убрать клише", tagline: "Текст без штампов" },
    "ur-pk": { icon: "🧹", name: "کلشے صاف کرنے والا", tagline: "گھسے پٹے جملے تلاش کر کے بہتر بنائیں" },
  },
  diff: {
    en: { icon: "⚖️", name: "Text Diff Checker", tagline: "Compare two texts side by side" },
    es: { icon: "⚖️", name: "Comparador de Texto", tagline: "Compara dos textos lado a lado" },
    ur: { icon: "⚖️", name: "Text Diff Checker", tagline: "Do tehreeron ka mawazna karen" },
    de: { icon: "⚖️", name: "Text-Vergleich", tagline: "Zwei Texte vergleichen" },
    fr: { icon: "⚖️", name: "Comparateur de Texte", tagline: "Comparez deux textes" },
    tr: { icon: "⚖️", name: "Metin Karşılaştırıcı", tagline: "İki metni karşılaştırın" },
    pt: { icon: "⚖️", name: "Comparador de Texto", tagline: "Compare dois textos" },
    ja: { icon: "⚖️", name: "テキスト比較", tagline: "2つの文章を比較" },
    no: { icon: "⚖️", name: "Tekstsammenligner", tagline: "Sammenlign to tekster" },
    nl: { icon: "⚖️", name: "Tekstvergelijker", tagline: "Vergelijk twee teksten" },
    it: { icon: "⚖️", name: "Confronto Testi", tagline: "Confronta due testi" },
    ru: { icon: "⚖️", name: "Сравнение текстов", tagline: "Найти различия в текстах" },
    "ur-pk": { icon: "⚖️", name: "فرق جانچنے والا", tagline: "دو متنوں کا فرق قطار بہ قطار دیکھیں" },
  },
};

const FREE_BADGE: Record<LanguageCode, string> = {
  en: "Free", es: "Gratis", ur: "Muft", de: "Kostenlos",
  fr: "Gratuit", tr: "Ücretsiz", pt: "Grátis", ja: "無料",
  no: "Gratis", nl: "Gratis", it: "Gratis", ru: "Бесплатно", "ur-pk": "مفت", hi: "मुफ़्त",
};

// Map tool to its guide article slug (Urdu guides exist for all)
const TOOL_ARTICLE_SLUG: Record<string, string> = {
  humanizer: "ai-text-ko-insani-banana-urdu-guide",
  detector: "ai-detector-urdu-guide",
  citation: "citation-generator-urdu-guide",
  expander: "sentence-expander-urdu-guide",
  summarizer: "text-summarizer-urdu-guide",
  voiceTyping: "voice-typing-urdu-guide",
  cvBuilder: "cv-builder-urdu-guide",
  wordCounter: "word-counter-urdu-guide",
  characterCounter: "character-counter-urdu-guide",
  textToSpeech: "text-to-speech-urdu-guide",
  typingTest: "typing-test-urdu-guide",
  caseConverter: "case-converter-urdu-guide",
  passwordGenerator: "password-generator-urdu-guide",
  duplicateLines: "remove-duplicate-lines-urdu-guide",
  textRepeater: "text-repeater-urdu-guide",
  invisibleCharacter: "invisible-character-urdu-guide",
  wordFrequency: "word-frequency-counter-urdu-guide",
  readingTime: "reading-time-calculator-urdu-guide",
  slugGenerator: "slug-generator-urdu-guide",
  jsonFormatter: "json-formatter-urdu-guide",
  loremIpsum: "lorem-ipsum-generator-urdu-guide",
  daysBetween: "days-between-dates-urdu-guide",
  randomNumber: "random-number-generator-urdu-guide",
  invoiceGenerator: "invoice-generator-urdu-guide",
  imageResizer: "image-resizer-urdu-guide",
  imageConverter: "image-converter-urdu-guide",
  imageToText: "image-to-text-urdu-guide",
  pdfSplitter: "pdf-splitter-urdu-guide",
  usernameGenerator: "username-generator-urdu-guide",
  morseCodeTranslator: "morse-code-translator-urdu-guide",
  voiceRecorder: "online-voice-recorder-urdu-guide",
  onlineNotepad: "online-notepad-urdu-guide",
  unitConverter: "unit-converter-urdu-guide",
  onlineTeleprompter: "online-teleprompter-urdu-guide",
  uuidGenerator: "uuid-generator-urdu-guide",
  timestampConverter: "unix-timestamp-converter-urdu-guide",
  jsonToCsv: "json-to-csv-converter-urdu-guide",
  regexTester: "regex-tester-urdu-guide",
  urlEncoder: "url-encoder-decoder-urdu-guide",
  utmLinkBuilder: "utm-link-builder-urdu-guide",
  metaChecker: "meta-title-description-checker-urdu-guide",
  onlineTimer: "online-timer-urdu-guide",
  instagramLineBreak: "instagram-line-break-urdu-guide",
  imageCompressor: "image-compressor-urdu-guide",
  pdfTools: "pdf-tools-urdu-guide",
  audioToText: "audio-to-text-converter-urdu-guide",
  backgroundRemover: "background-remover-urdu-guide",
  media: "video-tools-urdu-guide",
  seo: "seo-tools-urdu-guide",
  cleaner: "cliche-cleaner-urdu-guide",
  diff: "diff-checker-urdu-guide",
  voiceCloner: "voice-cloner-guide",
  museAiHub: "muse-ai-availability-checker-guide",
};

const GUIDE_TEXT: Record<LanguageCode, string> = {
  en: "📖 Read Guide", es: "📖 Leer Guía", ur: "📖 Guide Parhen",
  de: "📖 Anleitung", fr: "📖 Lire le Guide", tr: "📖 Rehberi Oku",
  pt: "📖 Ler Guia", ja: "📖 ガイドを読む", no: "📖 Les Guide",
  nl: "📖 Lees Gids", it: "📖 Leggi Guida", ru: "📖 Читать руководство", "ur-pk": "📖 رہنما پڑھیں", hi: "📖 गाइड पढ़ें",
};

const PRIVATE_BADGE: Record<LanguageCode, string> = {
  en: "Private", es: "Privado", ur: "Mehfooz", de: "Privat",
  fr: "Privé", tr: "Gizli", pt: "Privado", ja: "プライベート",
  no: "Privat", nl: "Privé", it: "Privato", ru: "Приватно", "ur-pk": "محفوظ", hi: "प्राइवेट",
};

interface Props {
  toolId: string;
  selectedLanguage?: LanguageCode;
}

export function MobileToolHero({ toolId, selectedLanguage = "en" }: Props) {
  const data = HERO_DATA[toolId]?.[selectedLanguage] || HERO_DATA[toolId]?.en;
  if (!data) return null;

  return (
    <div className="w-full bg-gradient-to-br from-amber-100 via-yellow-50 to-amber-50 text-stone-900 px-4 pt-5 pb-6 sm:hidden shadow-lg relative overflow-hidden border-b border-amber-200">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.15),transparent_50%)] pointer-events-none" />
      <div className="flex items-center gap-3 relative">
        <div className="text-4xl">{data.icon}</div>
        <div className="flex-1 min-w-0">
          <h1 className="text-xl font-bold leading-tight">{data.name}</h1>
          <p className="text-sm text-stone-600 leading-snug mt-0.5">{data.tagline}</p>
        </div>
      </div>
      <div className="flex gap-1.5 mt-3 relative flex-wrap">
        <span className="text-[11px] font-semibold bg-white/20 px-2 py-1 rounded-full whitespace-nowrap">
          ✓ {FREE_BADGE[selectedLanguage]}
        </span>
        <span className="text-[11px] font-semibold bg-white/20 px-2 py-1 rounded-full whitespace-nowrap">
          🔒 {PRIVATE_BADGE[selectedLanguage]}
        </span>
        {TOOL_ARTICLE_SLUG[toolId] && (
          <a
            href={`/${selectedLanguage}/blog/${TOOL_ARTICLE_SLUG[toolId]}/`}
            className="text-[11px] font-bold bg-white text-emerald-700 px-2.5 py-1 rounded-full hover:bg-emerald-50 transition-colors whitespace-nowrap"
          >
            {GUIDE_TEXT[selectedLanguage]}
          </a>
        )}
      </div>
    </div>
  );
}
