import React from "react";
import {
  Search,
  Video,
  Tag,
  ArrowRight,
  ShieldCheck,
  Sparkles,
  Zap,
  CheckCircle2,
  TrendingUp,
  BookMarked,
  CalendarDays,
  Dices,
  Maximize2,
  FileText,
  Scaling,
  AlertOctagon,
  GitCompare,
  Mic,
  Briefcase,
  Hash,
  Volume2,
  Keyboard,
  Type,
  KeyRound,
  ListChecks,
  Ghost,
  Repeat,
  LetterText,
  BarChart3,
  Timer,
  Binary,
  Instagram,
  Link2,
  Braces,
  AlignLeft,
  ScanText,
  Scissors,
  AtSign,
  Radio,
  Ruler,
  Fingerprint,
  Clock3,
  Table2,
  Regex,
  Megaphone,
  FileAudio,
} from "lucide-react";
import { ActivePage } from "../types";
import { findBlogPostBySlug } from "../data/blogArticles";
import { BookOpen } from "lucide-react";

import { LanguageCode } from "../types";
import { TRANSLATIONS } from "../data/translations";

interface OtherToolsSectionProps {
  activePage: ActivePage;
  onSelectPage: (page: ActivePage) => void;
  selectedLanguage?: LanguageCode;
}

export function OtherToolsSection({ activePage, onSelectPage, selectedLanguage = "en" }: OtherToolsSectionProps) {
  const t = TRANSLATIONS[selectedLanguage] || TRANSLATIONS.en;
  const ot = (t as any).otherTools || {};
  // Define all available tools
  const allTools = [
    {
      id: "humanizer" as ActivePage,
      title: "AI Text Humanizer",
      subtitle: "Natural, Human-Sounding Rewrites",
      badge: "⭐ Free",
      badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
      iconBg: "bg-gradient-to-tr from-emerald-500 to-teal-400 text-stone-950",
      cardBorder: "hover:border-emerald-500 hover:shadow-emerald-500/10",
      ctaBg: "bg-emerald-600 hover:bg-emerald-500 text-white",
      icon: Sparkles,
      desc: "Rewrite AI-assisted drafts into clearer, more natural-sounding text with varied sentence rhythm.",
      bullets: ["Natural Sentence Flow", "5 Writing Tone Styles", "Word (.doc) & TXT Export"],
      stat: "Free",
    },
    {
      id: "detector" as ActivePage,
      title: "AI Content Detector",
      subtitle: "Sentence-by-Sentence AI Heatmap",
      badge: "🔍 Heuristic Scan",
      badgeColor: "bg-cyan-100 text-cyan-800 border-cyan-300",
      iconBg: "bg-gradient-to-tr from-cyan-500 to-blue-500 text-white",
      cardBorder: "hover:border-cyan-500 hover:shadow-cyan-500/10",
      ctaBg: "bg-cyan-600 hover:bg-cyan-500 text-white",
      icon: Search,
      desc: "Analyze any document with our own heuristic model. It highlights robotic vs. natural sentences in red and green. Note: a heuristic estimate, not an official detector verdict.",
      bullets: ["Red & Green Pattern Heatmap", "Sentence-by-Sentence Analysis", "Send to Humanizer"],
      stat: "Heuristic Scan",
    },
    {
      id: "citation" as ActivePage,
      title: "Academic Citation & Reference Generator",
      subtitle: "APA 7, MLA 9, Chicago & Harvard",
      badge: "📚 Instant Bibliography",
      badgeColor: "bg-indigo-100 text-indigo-800 border-indigo-300",
      iconBg: "bg-gradient-to-tr from-indigo-500 to-purple-500 text-white",
      cardBorder: "hover:border-indigo-500 hover:shadow-indigo-500/10",
      ctaBg: "bg-indigo-600 hover:bg-indigo-500 text-white",
      icon: BookMarked,
      desc: "Format references for journal papers, books, websites, and theses from the source details you enter.",
      bullets: ["APA 7th & MLA 9th Formats", "Consistent Formatting", "Copy Citation"],
      stat: "APA & MLA 9",
    },
    {
      id: "expander" as ActivePage,
      title: "Academic Sentence Expander",
      subtitle: "Expand Short Sentences Into Fuller Paragraphs",
      badge: "📈 3 Depth Levels",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-500 to-fuchsia-500 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-600 hover:bg-violet-500 text-white",
      icon: Maximize2,
      desc: "Lengthen short sentences into fuller paragraphs with added detail and varied sentence lengths. Review facts and tone before use.",
      bullets: ["3 Depth Levels", "Varied Sentence Lengths", "Review Before Use"],
      stat: "3 Levels",
    },
    {
      id: "summarizer" as ActivePage,
      title: "AI Text Summarizer",
      subtitle: "Instant Extractive Summaries",
      badge: "⚡ 8 Languages",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-600 to-purple-500 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-600 hover:bg-violet-500 text-white",
      icon: FileText,
      desc: "Paste long articles, papers, or documents and get extractive summaries made from the source's own sentences.",
      bullets: ["3 Length Options", "Key Points Extraction", "100% Client-Side"],
      stat: "8 Languages",
    },
    {
      id: "voiceTyping" as ActivePage,
      title: "Voice Typing – Speech to Text",
      subtitle: "Speak in 11+ Languages",
      badge: "🎙️ Browser Mic",
      badgeColor: "bg-teal-100 text-teal-800 border-teal-300",
      iconBg: "bg-gradient-to-tr from-teal-500 to-emerald-500 text-white",
      cardBorder: "hover:border-teal-500 hover:shadow-teal-500/10",
      ctaBg: "bg-teal-600 hover:bg-teal-500 text-white",
      icon: Mic,
      desc: "Press the mic and talk — your words become text you can copy or polish. Great for essays, messages, and notes when typing is slow.",
      bullets: ["Urdu, English & More", "Live Transcript", "Copy or Download"],
      stat: "No Install",
    },
    {
      id: "cvBuilder" as ActivePage,
      title: "CV Builder – Resume Maker",
      subtitle: "Professional CV in Minutes",
      badge: "💼 Print & PDF",
      badgeColor: "bg-indigo-100 text-indigo-800 border-indigo-300",
      iconBg: "bg-gradient-to-tr from-indigo-500 to-blue-500 text-white",
      cardBorder: "hover:border-indigo-500 hover:shadow-indigo-500/10",
      ctaBg: "bg-indigo-600 hover:bg-indigo-500 text-white",
      icon: Briefcase,
      desc: "Fill in your details, watch the CV build itself, then print it or save it as a PDF. Everything stays on your device — nothing is uploaded.",
      bullets: ["2 Clean Templates", "Live Preview", "Private - On-Device"],
      stat: "No Sign-Up",
    },
    {
      id: "wordCounter" as ActivePage,
      title: "Word Counter",
      subtitle: "Words, Characters & Reading Time",
      badge: "🔢 Live Count",
      badgeColor: "bg-lime-100 text-lime-800 border-lime-300",
      iconBg: "bg-gradient-to-tr from-lime-500 to-emerald-500 text-white",
      cardBorder: "hover:border-lime-500 hover:shadow-lime-500/10",
      ctaBg: "bg-lime-600 hover:bg-lime-500 text-white",
      icon: Hash,
      desc: "Paste or type text and see words, characters, sentences, paragraphs and reading time update live in your browser.",
      bullets: ["Goal & Selection Count", "Top Repeated Words", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "characterCounter" as ActivePage,
      title: "Character Counter",
      subtitle: "Exact Characters & Platform Limits",
      badge: "🔠 Limit Check",
      badgeColor: "bg-sky-100 text-sky-800 border-sky-300",
      iconBg: "bg-gradient-to-tr from-sky-500 to-cyan-500 text-white",
      cardBorder: "hover:border-sky-500 hover:shadow-sky-500/10",
      ctaBg: "bg-sky-600 hover:bg-sky-500 text-white",
      icon: LetterText,
      desc: "Characters with and without spaces, Unicode code points, UTF-16 units and UTF-8 bytes, checked live against X, Instagram, LinkedIn, meta and SMS limits — fully in your browser.",
      bullets: ["4 Counting Methods, Labelled", "Platform Limit Presets", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "textToSpeech" as ActivePage,
      title: "Text to Speech",
      subtitle: "Hear Your Text Read Aloud",
      badge: "🔊 Device Voices",
      badgeColor: "bg-sky-100 text-sky-800 border-sky-300",
      iconBg: "bg-gradient-to-tr from-sky-500 to-cyan-500 text-white",
      cardBorder: "hover:border-sky-500 hover:shadow-sky-500/10",
      ctaBg: "bg-sky-600 hover:bg-sky-500 text-white",
      icon: Volume2,
      desc: "Paste text and your device reads it aloud with its own voices. Pick a voice, set speed and pitch — nothing is uploaded.",
      bullets: ["Speed & Pitch Control", "Long-Text Friendly", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "typingTest" as ActivePage,
      title: "Typing Speed Test",
      subtitle: "WPM, Accuracy & Typing Practice",
      badge: "⌨️ 11 Languages",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-500 to-purple-500 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-600 hover:bg-violet-500 text-white",
      icon: Keyboard,
      desc: "Take a 30 or 60 second test, or type 25 or 50 words, and see live WPM, accuracy and character stats. Original practice texts in 11 languages, including Roman Urdu.",
      bullets: ["30s / 60s / 25 / 50 Modes", "Live WPM & Accuracy", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "caseConverter" as ActivePage,
      title: "Case Converter",
      subtitle: "UPPERCASE, lowercase & Title Case",
      badge: "🔤 7 Cases",
      badgeColor: "bg-cyan-100 text-cyan-800 border-cyan-300",
      iconBg: "bg-gradient-to-tr from-cyan-500 to-teal-500 text-white",
      cardBorder: "hover:border-cyan-500 hover:shadow-cyan-500/10",
      ctaBg: "bg-cyan-600 hover:bg-cyan-500 text-white",
      icon: Type,
      desc: "Change text to UPPERCASE, lowercase, Sentence case, Capitalized Case, Title Case, alternating or inverse case. Locale-aware, with live counts — fully in your browser.",
      bullets: ["7 One-Click Cases", "Live Counts & Preview", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "passwordGenerator" as ActivePage,
      title: "Password Generator",
      subtitle: "Strong Random Passwords, On-Device",
      badge: "🔑 Crypto Random",
      badgeColor: "bg-indigo-100 text-indigo-800 border-indigo-300",
      iconBg: "bg-gradient-to-tr from-indigo-500 to-blue-600 text-white",
      cardBorder: "hover:border-indigo-500 hover:shadow-indigo-500/10",
      ctaBg: "bg-indigo-600 hover:bg-indigo-500 text-white",
      icon: KeyRound,
      desc: "Create strong random passwords with length and character controls, look-alike exclusion and an honest entropy estimate. Made on your device — never uploaded or stored.",
      bullets: ["Crypto-Random (Web Crypto)", "Up to 20 at Once", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "duplicateLines" as ActivePage,
      title: "Remove Duplicate Lines",
      subtitle: "Keep the First Copy of Every Line",
      badge: "🧾 Live Counts",
      badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
      iconBg: "bg-gradient-to-tr from-emerald-500 to-teal-500 text-white",
      cardBorder: "hover:border-emerald-500 hover:shadow-emerald-500/10",
      ctaBg: "bg-emerald-600 hover:bg-emerald-500 text-white",
      icon: ListChecks,
      desc: "Paste a list or open a .txt file and remove repeated lines while keeping the first occurrence. Control case, edge spaces, blank lines and A–Z sorting — fully in your browser.",
      bullets: ["First Occurrence Kept", "Case, Trim, Blank & Sort Controls", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "invisibleCharacter" as ActivePage,
      title: "Invisible Character",
      subtitle: "Copy Blank Text & Reveal Hidden Text",
      badge: "👻 Unicode Tester",
      badgeColor: "bg-fuchsia-100 text-fuchsia-800 border-fuchsia-300",
      iconBg: "bg-gradient-to-tr from-fuchsia-500 to-purple-500 text-white",
      cardBorder: "hover:border-fuchsia-500 hover:shadow-fuchsia-500/10",
      ctaBg: "bg-fuchsia-700 hover:bg-fuchsia-600 text-white",
      icon: Ghost,
      desc: "Copy genuinely invisible or blank-width Unicode characters, generate blank text by count, and reveal hidden characters in pasted text with code-point labels — fully in your browser.",
      bullets: ["Zero-Width & Blank-Width Choices", "Visible Code-Point Tester", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "wordFrequency" as ActivePage,
      title: "Word Frequency Counter",
      subtitle: "Rank Repeated Words & Phrases",
      badge: "📊 CSV Export",
      badgeColor: "bg-indigo-100 text-indigo-800 border-indigo-300",
      iconBg: "bg-gradient-to-tr from-indigo-500 to-violet-500 text-white",
      cardBorder: "hover:border-indigo-500 hover:shadow-indigo-500/10",
      ctaBg: "bg-indigo-600 hover:bg-indigo-500 text-white",
      icon: BarChart3,
      desc: "Rank the words and 1–3 word phrases you repeat most, with counts, percentages, transparent filters and highlighted matches — fully in your browser.",
      bullets: ["Ranked Table & Percentages", "Copy Table or CSV", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "readingTime" as ActivePage,
      title: "Reading Time Calculator",
      subtitle: "Reading & Speaking Time",
      badge: "⏱️ Adjustable WPM",
      badgeColor: "bg-teal-100 text-teal-800 border-teal-300",
      iconBg: "bg-gradient-to-tr from-teal-500 to-emerald-500 text-white",
      cardBorder: "hover:border-teal-500 hover:shadow-teal-500/10",
      ctaBg: "bg-teal-600 hover:bg-teal-500 text-white",
      icon: Timer,
      desc: "Estimate how long your text takes to read silently or say aloud, with adjustable words-per-minute speeds and a presentation pause allowance — fully in your browser.",
      bullets: ["Reading & Speaking Modes", "Pause Allowance for Speeches", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "base64" as ActivePage,
      title: "Base64 Encoder & Decoder",
      subtitle: "UTF-8 Text & URL-Safe",
      badge: "🔐 Not Encryption",
      badgeColor: "bg-indigo-100 text-indigo-800 border-indigo-300",
      iconBg: "bg-gradient-to-tr from-indigo-500 to-blue-500 text-white",
      cardBorder: "hover:border-indigo-500 hover:shadow-indigo-500/10",
      ctaBg: "bg-indigo-600 hover:bg-indigo-500 text-white",
      icon: Binary,
      desc: "Encode and decode Base64 with UTF-8-safe text, URL-safe mode, clear invalid-input errors and a small-file option — fully in your browser.",
      bullets: ["UTF-8, Emoji & Scripts", "Standard & URL-Safe", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "slugGenerator" as ActivePage,
      title: "Slug Generator",
      subtitle: "Titles into Clean URLs",
      badge: "🔗 Batch Mode",
      badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
      iconBg: "bg-gradient-to-tr from-emerald-500 to-teal-500 text-white",
      cardBorder: "hover:border-emerald-500 hover:shadow-emerald-500/10",
      ctaBg: "bg-emerald-600 hover:bg-emerald-500 text-white",
      icon: Link2,
      desc: "Paste a title and copy a lowercase URL slug: hyphen or underscore separators, English stop-word removal, accent handling, length limit and one-title-per-line batch mode — fully in your browser.",
      bullets: ["Hyphens or Underscores", "Batch: One Title per Line", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "jsonFormatter" as ActivePage,
      title: "JSON Formatter",
      subtitle: "Beautify, Minify & Validate",
      badge: "🧩 Tree View",
      badgeColor: "bg-sky-100 text-sky-800 border-sky-300",
      iconBg: "bg-gradient-to-tr from-sky-500 to-blue-600 text-white",
      cardBorder: "hover:border-sky-500 hover:shadow-sky-500/10",
      ctaBg: "bg-sky-700 hover:bg-sky-600 text-white",
      icon: Braces,
      desc: "Beautify JSON with 2 or 4 spaces or tabs, minify it to one line, validate with honest parser positions, and inspect it as a collapsible tree — fully in your browser.",
      bullets: ["2 / 4 Spaces or Tab", "Collapsible Tree View", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "loremIpsum" as ActivePage,
      title: "Lorem Ipsum Generator",
      subtitle: "Placeholder Paragraphs & Words",
      badge: "📄 HTML & List Output",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-500 to-purple-600 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-700 hover:bg-violet-600 text-white",
      icon: AlignLeft,
      desc: "Generate classic lorem ipsum paragraphs, sentences or an exact word count as plain text, HTML paragraphs or a list — with the famous opening line on or off, plus copy and download.",
      bullets: ["Paragraphs / Sentences / Words", "Plain, HTML or List", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "daysBetween" as ActivePage,
      title: "Days Between Dates",
      subtitle: "Count Days & Business Days",
      badge: "📅 Incl./Excl. Toggle",
      badgeColor: "bg-sky-100 text-sky-800 border-sky-300",
      iconBg: "bg-gradient-to-tr from-sky-500 to-blue-600 text-white",
      cardBorder: "hover:border-sky-500 hover:shadow-sky-500/10",
      ctaBg: "bg-sky-700 hover:bg-sky-600 text-white",
      icon: CalendarDays,
      desc: "Count the days between two dates — inclusive or exclusive — with whole weeks, approximate months/years and Monday–Friday business days (public holidays are never subtracted). UTC date math, fully in your browser.",
      bullets: ["Inclusive / Exclusive Counting", "Business Days, No Holidays", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "randomNumber" as ActivePage,
      title: "Random Number Generator",
      subtitle: "Numbers, Coin Flip & Dice",
      badge: "🎲 Crypto Random",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-500 to-purple-600 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-700 hover:bg-violet-600 text-white",
      icon: Dices,
      desc: "Draw random numbers in any range — repeats on or off, sorted or in draw order — with a session history, coin flip and dice roller in the same tool. Browser cryptographic randomness, fully in your tab.",
      bullets: ["Unique Draws & Sorting", "Coin Flip & Dice Modes", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "onlineTimer" as ActivePage,
      title: "Online Timer & Stopwatch",
      subtitle: "Countdown, Laps & Big Digits",
      badge: "⏱️ Timestamp True",
      badgeColor: "bg-teal-100 text-teal-800 border-teal-300",
      iconBg: "bg-gradient-to-tr from-teal-500 to-emerald-600 text-white",
      cardBorder: "hover:border-teal-500 hover:shadow-teal-500/10",
      ctaBg: "bg-teal-700 hover:bg-teal-600 text-white",
      icon: Timer,
      desc: "Countdown timer with presets plus a stopwatch with laps in one tool — big readable digits, timestamp-based timing, sound and screen flash at zero. Fully in your browser.",
      bullets: ["Countdown Presets & +1 Min", "Stopwatch Laps, Copy Table", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "invoiceGenerator" as ActivePage,
      title: "Invoice Generator",
      subtitle: "Items, Discount, Tax & PDF",
      badge: "🧾 No Sign-Up",
      badgeColor: "bg-teal-100 text-teal-800 border-teal-300",
      iconBg: "bg-gradient-to-tr from-teal-500 to-emerald-600 text-white",
      cardBorder: "hover:border-teal-500 hover:shadow-teal-500/10",
      ctaBg: "bg-teal-700 hover:bg-teal-600 text-white",
      icon: FileText,
      desc: "Build a printable invoice from your details and line items: subtotal, discount and tax shown step by step in your currency, with on-device autosave and print to PDF. A document maker, not tax advice.",
      bullets: ["Live Totals, Shown Step by Step", "Print / Save as PDF", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "imageResizer" as ActivePage,
      title: "Image Resizer & Cropper",
      subtitle: "Exact Pixels, Crop & Presets",
      badge: "🖼️ Fully Local",
      badgeColor: "bg-teal-100 text-teal-800 border-teal-300",
      iconBg: "bg-gradient-to-tr from-teal-500 to-emerald-600 text-white",
      cardBorder: "hover:border-teal-500 hover:shadow-teal-500/10",
      ctaBg: "bg-teal-700 hover:bg-teal-600 text-white",
      icon: Scaling,
      desc: "Resize one photo by exact pixels or percentage, crop to 1:1, 4:5, 16:9 and other ratios, use Instagram, YouTube, X and A4 presets, then download JPG, PNG or WebP — decoded and encoded in your browser, never uploaded.",
      bullets: ["Exact Pixels, % & Ratio Crop", "Social & A4 Presets", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "imageConverter" as ActivePage,
      title: "Image Converter",
      subtitle: "JPG, PNG & WebP, Same Size",
      badge: "🔁 Batch Local",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-500 to-purple-600 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-700 hover:bg-violet-600 text-white",
      icon: Repeat,
      desc: "Convert one photo or a whole queue between JPG, PNG and WebP at the exact same dimensions: quality slider, a background colour when JPG must flatten transparency, per-file detected format and before/after sizes — decoded and encoded in your browser, never uploaded. HEIC is honestly flagged when a browser cannot read it.",
      bullets: ["Batch Queue, One Format", "JPG Background Choice", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "imageToText" as ActivePage,
      title: "Image to Text OCR",
      subtitle: "Extract Text from JPG, PNG & WebP",
      badge: "🔍 Local OCR",
      badgeColor: "bg-cyan-100 text-cyan-800 border-cyan-300",
      iconBg: "bg-gradient-to-tr from-cyan-500 to-sky-600 text-white",
      cardBorder: "hover:border-cyan-500 hover:shadow-cyan-500/10",
      ctaBg: "bg-cyan-700 hover:bg-cyan-600 text-white",
      icon: ScanText,
      desc: "Read printed text out of one photo, screenshot or scan with the open-source Tesseract OCR engine, running in your browser: pick the language of the text, watch real progress, then edit, copy or download the result. Your image never leaves your device; the engine and language data download once from a CDN on first use.",
      bullets: ["11 OCR Languages", "Editable Text, Copy & .txt", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "pdfSplitter" as ActivePage,
      title: "PDF Splitter",
      subtitle: "Extract Pages & Split Ranges",
      badge: "✂️ Local Split",
      badgeColor: "bg-orange-100 text-orange-800 border-orange-300",
      iconBg: "bg-gradient-to-tr from-orange-500 to-amber-600 text-white",
      cardBorder: "hover:border-orange-500 hover:shadow-orange-500/10",
      ctaBg: "bg-orange-700 hover:bg-orange-600 text-white",
      icon: Scissors,
      desc: "Pull the pages you need out of one PDF: type ranges like 1-3, 5, 8-10 and get one combined PDF or a separate PDF per range, built locally with pdf-lib. Your file is never uploaded, the real page count is shown before you split, and password-protected or damaged PDFs fail with a clear message instead of a fake result.",
      bullets: ["Range Builder 1-3, 5, 8", "One PDF or Per-Range PDFs", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "usernameGenerator" as ActivePage,
      title: "Username Generator",
      subtitle: "Themes, Seed Words & Favourites",
      badge: "@ Local Ideas",
      badgeColor: "bg-fuchsia-100 text-fuchsia-800 border-fuchsia-300",
      iconBg: "bg-gradient-to-tr from-fuchsia-500 to-pink-600 text-white",
      cardBorder: "hover:border-fuchsia-500 hover:shadow-fuchsia-500/10",
      ctaBg: "bg-fuchsia-700 hover:bg-fuchsia-600 text-white",
      icon: AtSign,
      desc: "Brainstorm 20 clean username ideas from gaming, creator, study, business, aesthetic and funny word banks. Add an optional seed word, choose numbers, separators and length, then copy and favourite finalists. Availability is deliberately not checked, so verify each name on the platform and check trademarks before using it.",
      bullets: ["Batch of 20 Ideas", "Character Count & Copy", "Favourites in This Tab"],
      stat: "No Sign-Up",
    },
    {
      id: "morseCodeTranslator" as ActivePage,
      title: "Morse Code Translator",
      subtitle: "Text ↔ Morse, Sound & Flash",
      badge: "📡 Local Morse",
      badgeColor: "bg-cyan-100 text-cyan-800 border-cyan-300",
      iconBg: "bg-gradient-to-tr from-cyan-500 to-sky-600 text-white",
      cardBorder: "hover:border-cyan-500 hover:shadow-cyan-500/10",
      ctaBg: "bg-cyan-700 hover:bg-cyan-600 text-white",
      icon: Radio,
      desc: "Convert text to Morse code and Morse back to text, live as you type. Play the beeps at your own speed from 5 to 40 WPM, watch the lamp flash in time (with a photosensitivity warning), copy either direction, and check the full A–Z, 0–9 and punctuation chart. Unsupported characters are listed, never silently changed, and everything stays in your browser.",
      bullets: ["Live Both Directions", "5–40 WPM Playback", "Full Morse Chart"],
      stat: "No Sign-Up",
    },
    {
      id: "voiceRecorder" as ActivePage,
      title: "Online Voice Recorder",
      subtitle: "Record, Pause, Play & Download",
      badge: "🎙️ No Upload",
      badgeColor: "bg-rose-100 text-rose-800 border-rose-300",
      iconBg: "bg-gradient-to-tr from-rose-500 to-orange-500 text-white",
      cardBorder: "hover:border-rose-500 hover:shadow-rose-500/10",
      ctaBg: "bg-rose-700 hover:bg-rose-600 text-white",
      icon: Mic,
      desc: "Record your voice right in the browser with pause and resume, a live timer and level meter, then play the take back and download it. The recording never leaves your device, and the saved file honestly uses your browser's real format (WebM or MP4) — never a fake MP3 promise. A consent reminder keeps recordings of other people on the right side of permission.",
      bullets: ["Pause & Resume", "Real Format Label", "Stays On Device"],
      stat: "No Sign-Up",
    },
    {
      id: "onlineNotepad" as ActivePage,
      title: "Online Notepad",
      subtitle: "Autosave Notes, Counts & .txt Download",
      badge: "📝 Browser Only",
      badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
      iconBg: "bg-gradient-to-tr from-emerald-500 to-teal-500 text-white",
      cardBorder: "hover:border-emerald-500 hover:shadow-emerald-500/10",
      ctaBg: "bg-emerald-700 hover:bg-emerald-600 text-white",
      icon: FileText,
      desc: "Open and type instantly: several titled notes autosave in this browser with live word and character counts, copy and .txt download. Notes stay on this device only, never uploaded, with a clear warning to keep passwords and secrets out.",
      bullets: ["Autosave, Restored on Reopen", "Live Word & Character Counts", "Stays On This Device"],
      stat: "No Sign-Up",
    },
    {
      id: "unitConverter" as ActivePage,
      title: "Unit Converter",
      subtitle: "Length, Weight, Temp & More",
      badge: "📏 No Currency",
      badgeColor: "bg-sky-100 text-sky-800 border-sky-300",
      iconBg: "bg-gradient-to-tr from-sky-500 to-cyan-600 text-white",
      cardBorder: "hover:border-sky-500 hover:shadow-sky-500/10",
      ctaBg: "bg-sky-700 hover:bg-sky-600 text-white",
      icon: Ruler,
      desc: "Convert length, weight, temperature, volume, area, speed, time, data, pressure and energy with established SI/NIST factors, the formula shown with every result, a swap button and school/cooking/travel presets. Currency is deliberately excluded because money needs live rates, and nothing is uploaded.",
      bullets: ["10 Everyday Categories", "Formula With Every Result", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "onlineTeleprompter" as ActivePage,
      title: "Online Teleprompter",
      subtitle: "Scrolling Script, Mirror & Countdown",
      badge: "🎬 Text Only",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-500 to-purple-600 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-700 hover:bg-violet-600 text-white",
      icon: Video,
      desc: "Paste your script and read it as big, smooth scrolling text. Set speed and font size, add a 3-2-1 countdown, go fullscreen, flip for teleprompter glass, and see word count plus estimated speaking time. It never records, never uploads, and your script leaves with the tab.",
      bullets: ["Spacebar Play / Pause", "Mirror for Glass Rigs", "No Recording, No Upload"],
      stat: "No Sign-Up",
    },
    {
      id: "uuidGenerator" as ActivePage,
      title: "UUID Generator",
      subtitle: "Bulk v4, Case & Hyphens",
      badge: "🆔 V4 Only",
      badgeColor: "bg-indigo-100 text-indigo-800 border-indigo-300",
      iconBg: "bg-gradient-to-tr from-indigo-500 to-blue-600 text-white",
      cardBorder: "hover:border-indigo-500 hover:shadow-indigo-500/10",
      ctaBg: "bg-indigo-700 hover:bg-indigo-600 text-white",
      icon: Fingerprint,
      desc: "Mint random UUID version 4 identifiers in bulk — up to 100 at once — with uppercase and hyphen options, per-row copy and copy-all. Generated locally with Web Crypto: nothing uploaded, and honestly described as astronomically unlikely to collide, never impossible.",
      bullets: ["Bulk Up To 100", "Copy One or All", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "timestampConverter" as ActivePage,
      title: "Unix Timestamp Converter",
      subtitle: "Epoch, UTC & Local Side by Side",
      badge: "🕐 Unit Stated",
      badgeColor: "bg-teal-100 text-teal-800 border-teal-300",
      iconBg: "bg-gradient-to-tr from-teal-500 to-cyan-600 text-white",
      cardBorder: "hover:border-teal-500 hover:shadow-teal-500/10",
      ctaBg: "bg-teal-700 hover:bg-teal-600 text-white",
      icon: Clock3,
      desc: "Live epoch clock plus paste-a-timestamp conversion with the seconds-or-milliseconds assumption always shown, UTC and local side by side, copyable ISO 8601, and date-to-timestamp in seconds and milliseconds. Fully local.",
      bullets: ["Auto-Detect With Override", "UTC + Local + ISO Copy", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "jsonToCsv" as ActivePage,
      title: "JSON to CSV Converter",
      subtitle: "Flatten, Preview & Safe Export",
      badge: "📊 Rule Shown",
      badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
      iconBg: "bg-gradient-to-tr from-emerald-500 to-teal-600 text-white",
      cardBorder: "hover:border-emerald-500 hover:shadow-emerald-500/10",
      ctaBg: "bg-emerald-700 hover:bg-emerald-600 text-white",
      icon: Table2,
      desc: "Paste or upload JSON and convert an array of objects into CSV with dot-path flattening shown on screen, comma/semicolon/tab delimiters, a capped preview table, and safe export that escapes fields starting with =, +, - or @ so spreadsheets cannot run them as formulas. Fully local.",
      bullets: ["Dot-Path Flattening", "Formula-Safe Export", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "regexTester" as ActivePage,
      title: "Regex Tester",
      subtitle: "Matches, Groups & Replace",
      badge: "🔎 JS Flavour",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-500 to-purple-600 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-700 hover:bg-violet-600 text-white",
      icon: Regex,
      desc: "Test a JavaScript regular expression live: pattern and g/i/m/s/u/y flags, highlighted matches, a match list with index and captured groups, a replace preview, and common-pattern examples — with printed input caps and slow-pattern guidance. Fully local.",
      bullets: ["Live Highlighting", "Groups & Replace Preview", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "urlEncoder" as ActivePage,
      title: "URL Encoder / Decoder",
      subtitle: "Full Link or Single Value",
      badge: "🔗 Two Modes",
      badgeColor: "bg-sky-100 text-sky-800 border-sky-300",
      iconBg: "bg-gradient-to-tr from-sky-500 to-cyan-600 text-white",
      cardBorder: "hover:border-sky-500 hover:shadow-sky-500/10",
      ctaBg: "bg-sky-700 hover:bg-sky-600 text-white",
      icon: Link2,
      desc: "Encode or decode a full URL (encodeURI) or a single query value (encodeURIComponent) with a one-tap mode switch, live results, copy and swap-and-reverse, a worked example showing why & = ? corrupt a value in the wrong mode, and a plain-language error for invalid percent-sequences. Encoding is not encryption. Fully local.",
      bullets: ["Full URL & Component Modes", "Invalid-% Error Explained", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "utmLinkBuilder" as ActivePage,
      title: "UTM Link Builder",
      subtitle: "Source, Medium & Campaign Tags",
      badge: "📣 Device Presets",
      badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
      iconBg: "bg-gradient-to-tr from-emerald-500 to-teal-600 text-white",
      cardBorder: "hover:border-emerald-500 hover:shadow-emerald-500/10",
      ctaBg: "bg-emerald-700 hover:bg-emerald-600 text-white",
      icon: Megaphone,
      desc: "Build a campaign URL with utm_source, utm_medium, utm_campaign and optional term/content: live final-URL preview, encodeURIComponent-correct values, one-click copy, a lowercase naming warning, and presets saved only on your device. UTMs label the click — analytics setup, consent, redirects and platform stripping still decide whether it is reported.",
      bullets: ["Live Tagged-URL Preview", "On-Device Naming Presets", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "metaChecker" as ActivePage,
      title: "Meta Title & Description Checker",
      subtitle: "Length, Pixels & SERP Preview",
      badge: "🔍 SERP Preview",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-500 to-purple-600 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-700 hover:bg-violet-600 text-white",
      icon: Type,
      desc: "Check a meta title and description with live character counts, a canvas-measured approximate pixel width, and desktop + mobile SERP previews. Length bands are display guidance only — Google often rewrites titles and descriptions, so no display or ranking result is promised. Fully local.",
      bullets: ["Characters & Approx. Pixels", "Desktop & Mobile Preview", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "instagramLineBreak" as ActivePage,
      title: "Instagram Line Breaks",
      subtitle: "Keep Caption & Bio Spacing",
      badge: "📸 Live Preview",
      badgeColor: "bg-pink-100 text-pink-800 border-pink-300",
      iconBg: "bg-gradient-to-tr from-pink-500 to-purple-500 text-white",
      cardBorder: "hover:border-pink-500 hover:shadow-pink-500/10",
      ctaBg: "bg-pink-600 hover:bg-pink-500 text-white",
      icon: Instagram,
      desc: "Write captions and bios with real blank lines and copy them with the spacing protected by an invisible character. Live preview and character counts — fully in your browser.",
      bullets: ["Invisible Blank Lines", "Live Caption Preview", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "textRepeater" as ActivePage,
      title: "Text Repeater",
      subtitle: "Repeat Text Up to 1,000 Times",
      badge: "🔁 Honest Caps",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-500 to-purple-600 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-600 hover:bg-violet-500 text-white",
      icon: Repeat,
      desc: "Repeat any word, sentence or emoji up to 1,000 times with space, new-line, comma or custom separators — plus a repeat-each-word mode. Output capped honestly, fully in your browser.",
      bullets: ["Whole-Text & Per-Word Modes", "Copy or Download Result", "Private - In-Browser"],
      stat: "No Sign-Up",
    },
    {
      id: "cleaner" as ActivePage,
      title: "AI Cliché & Buzzword Checker",
      subtitle: "Find Repetitive AI-Style Phrases",
      badge: "🧹 Pattern Check",
      badgeColor: "bg-rose-100 text-rose-800 border-rose-300",
      iconBg: "bg-gradient-to-tr from-rose-500 to-red-500 text-white",
      cardBorder: "hover:border-rose-500 hover:shadow-rose-500/10",
      ctaBg: "bg-rose-600 hover:bg-rose-500 text-white",
      icon: AlertOctagon,
      desc: "Flags common AI-style clichés such as 'delve', 'tapestry', 'testament' and 'pivotal' so you can rewrite them in your own words.",
      bullets: ["Cliché Pattern Rules", "Review Each Match in Context", "Plain-Language Alternatives"],
      stat: "Pattern Check",
    },
    {
      id: "diff" as ActivePage,
      title: "Text Similarity & Diff Checker",
      subtitle: "Word-by-Word Comparison",
      badge: "⚖️ Word-by-Word Diff",
      badgeColor: "bg-blue-100 text-blue-800 border-blue-300",
      iconBg: "bg-gradient-to-tr from-blue-500 to-teal-500 text-white",
      cardBorder: "hover:border-blue-500 hover:shadow-blue-500/10",
      ctaBg: "bg-blue-600 hover:bg-blue-500 text-white",
      icon: GitCompare,
      desc: "Compare two versions side by side with a colour-coded word diff and an overlap estimate. It does not predict Turnitin or any other service.",
      bullets: ["Colour-Coded Inline Diff", "Added & Removed Words", "Wording Overlap Estimate"],
      stat: "Visual Diff",
    },
    {
      id: "media" as ActivePage,
      title: "Video & Image Media Tools",
      subtitle: "Crop, Pacing and Metadata Tools",
      badge: "🎬 TikTok & IG Shorts",
      badgeColor: "bg-rose-100 text-rose-800 border-rose-300",
      iconBg: "bg-gradient-to-tr from-rose-500 to-pink-500 text-white",
      cardBorder: "hover:border-rose-500 hover:shadow-rose-500/10",
      ctaBg: "bg-rose-600 hover:bg-rose-500 text-white",
      icon: Video,
      desc: "Crop edge areas, adjust pacing and work with image metadata in your browser. Use only media you own or have permission to edit.",
      bullets: ["Corner Crop & Masking", "Frame Pacing Controls", "Use Rights-Cleared Media Only"],
      stat: "Browser-Based",
    },
    {
      id: "seo" as ActivePage,
      title: "SEO Title, Meta & Hashtag Helper",
      subtitle: "Ideas for Pages and Short Videos",
      badge: "🚀 Idea Generator",
      badgeColor: "bg-amber-100 text-amber-800 border-amber-300",
      iconBg: "bg-gradient-to-tr from-amber-500 to-orange-500 text-stone-950",
      cardBorder: "hover:border-amber-500 hover:shadow-amber-500/10",
      ctaBg: "bg-amber-600 hover:bg-amber-500 text-white",
      icon: TrendingUp,
      desc: "Generate title ideas, meta-description drafts and hashtag suggestions. These are writing aids, not ranking or traffic guarantees.",
      bullets: ["Meta Title & Description Drafts", "Keyword & Hashtag Ideas", "Copy to Clipboard"],
      stat: "Free",
    },
    {
      id: "imageCompressor" as ActivePage,
      title: "Image Compressor",
      subtitle: "Reduce Image File Size",
      badge: "🖼️ Free & Fast",
      badgeColor: "bg-cyan-100 text-cyan-800 border-cyan-300",
      iconBg: "bg-gradient-to-tr from-cyan-500 to-blue-500 text-white",
      cardBorder: "hover:border-cyan-500 hover:shadow-cyan-500/10",
      ctaBg: "bg-cyan-600 hover:bg-cyan-500 text-white",
      icon: Maximize2,
      desc: "Compress JPEG, PNG, and WebP images right in your browser. Reduce file size for faster websites and smaller uploads.",
      bullets: ["Batch Image Processing", "Quality Control Slider", "Private - Never Uploaded"],
      stat: "Free",
    },
    {
      id: "pdfTools" as ActivePage,
      title: "PDF Tools",
      subtitle: "Merge PDFs & Create from Images",
      badge: "📕 Free & Private",
      badgeColor: "bg-red-100 text-red-800 border-red-300",
      iconBg: "bg-gradient-to-tr from-red-500 to-orange-500 text-white",
      cardBorder: "hover:border-red-500 hover:shadow-red-500/10",
      ctaBg: "bg-red-600 hover:bg-red-500 text-white",
      icon: FileText,
      desc: "Merge multiple PDFs into one file, or turn your photos into a PDF document. All in your browser.",
      bullets: ["Merge Multiple PDFs", "Images to PDF", "Private - Never Uploaded"],
      stat: "Free",
    },
    {
      id: "audioToText" as ActivePage,
      title: "Audio to Text Converter",
      subtitle: "Transcribe Recordings On Your Device",
      badge: "🎧 Free & Private",
      badgeColor: "bg-cyan-100 text-cyan-800 border-cyan-300",
      iconBg: "bg-gradient-to-tr from-cyan-500 to-sky-500 text-white",
      cardBorder: "hover:border-cyan-500 hover:shadow-cyan-500/10",
      ctaBg: "bg-cyan-600 hover:bg-cyan-500 text-white",
      icon: FileAudio,
      desc: "Turn MP3, WAV and M4A recordings into text with a speech model that runs in your browser. Your file never leaves your device.",
      bullets: ["On-Device Whisper AI", "TXT, SRT & VTT Export", "Works Offline After First Download"],
      stat: "Free",
    },
    {
      id: "backgroundRemover" as ActivePage,
      title: "Background Remover",
      subtitle: "Erase Photo Backgrounds on Your Device",
      badge: "✨ Free & Private",
      badgeColor: "bg-violet-100 text-violet-800 border-violet-300",
      iconBg: "bg-gradient-to-tr from-violet-500 to-fuchsia-500 text-white",
      cardBorder: "hover:border-violet-500 hover:shadow-violet-500/10",
      ctaBg: "bg-violet-600 hover:bg-violet-500 text-white",
      icon: Scissors,
      desc: "Extract subjects and save transparent PNGs with an in-browser AI model that processes photos locally without server uploads.",
      bullets: ["Local AI Model", "Full-Res Transparent PNGs", "Batch & Custom Colors"],
      stat: "Free",
    },
    {
      id: "voiceCloner" as ActivePage,
      title: "AI Voice Cloner",
      subtitle: "Hear Text — or Your Own Voice — Out Loud",
      badge: "🎙️ Free & Private",
      badgeColor: "bg-rose-100 text-rose-800 border-rose-300",
      iconBg: "bg-gradient-to-tr from-rose-500 to-orange-500 text-white",
      cardBorder: "hover:border-rose-500 hover:shadow-rose-500/10",
      ctaBg: "bg-rose-600 hover:bg-rose-500 text-white",
      icon: Mic,
      desc: "Hear any text in natural voices that run inside your browser, or clone your own voice from a 10-second recording. Free voices need no sign-up.",
      bullets: ["Natural Voices On-Device", "Clone From a 10s Clip", "Text Never Uploaded"],
      stat: "Free",
    },
    {
      id: "museAiHub" as ActivePage,
      title: "Muse AI Availability Checker",
      subtitle: "Is Meta's Muse AI Available in Your Country?",
      badge: "🌍 Free Checker",
      badgeColor: "bg-teal-100 text-teal-800 border-teal-300",
      iconBg: "bg-gradient-to-tr from-teal-600 to-cyan-500 text-white",
      cardBorder: "hover:border-teal-500 hover:shadow-teal-500/10",
      ctaBg: "bg-teal-600 hover:bg-teal-500 text-white",
      icon: Search,
      desc: "Check whether Meta's Muse AI has officially launched in your country — date-checked against Meta's own pages — plus honest tokens & plans info and a free prompt builder.",
      bullets: ["Checked Against Meta's Pages", "Tokens & Plans, Honestly", "Free Prompt Helper"],
      stat: "Free",
    },
  ];

  // Show all other tools (excluding current active page)
  const displayTools = allTools.filter((tool) => tool.id !== activePage);

  // Related guide article for current tool (language-aware)
  const TOOL_TO_ARTICLE_UR: Record<string, string> = {
    humanizer: "ai-humanizer-guide",
    detector: "ai-detector-urdu-guide",
    citation: "citation-generator-urdu-guide",
    expander: "sentence-expander-urdu-guide",
    summarizer: "text-summarizer-urdu-guide",
    voiceTyping: "voice-typing-urdu-guide",
    cvBuilder: "cv-builder-urdu-guide",
    wordCounter: "word-counter-urdu-guide",
    characterCounter: "character-counter-urdu-guide",
    textToSpeech: "text-to-speech-urdu-guide",
    typingTest: "typing-test-urdu-guide",
    caseConverter: "case-converter-urdu-guide",
    passwordGenerator: "password-generator-urdu-guide",
    duplicateLines: "remove-duplicate-lines-urdu-guide",
    textRepeater: "text-repeater-urdu-guide",
    invisibleCharacter: "invisible-character-urdu-guide",
    wordFrequency: "word-frequency-counter-urdu-guide",
    readingTime: "reading-time-calculator-urdu-guide",
    slugGenerator: "slug-generator-urdu-guide",
    jsonFormatter: "json-formatter-urdu-guide",
    loremIpsum: "lorem-ipsum-generator-urdu-guide",
    daysBetween: "days-between-dates-urdu-guide",
    randomNumber: "random-number-generator-urdu-guide",
    invoiceGenerator: "invoice-generator-urdu-guide",
    imageResizer: "image-resizer-urdu-guide",
    imageConverter: "image-converter-urdu-guide",
    imageToText: "image-to-text-urdu-guide",
    pdfSplitter: "pdf-splitter-urdu-guide",
    usernameGenerator: "username-generator-urdu-guide",
    morseCodeTranslator: "morse-code-translator-urdu-guide",
    voiceRecorder: "online-voice-recorder-urdu-guide",
    onlineNotepad: "online-notepad-urdu-guide",
    unitConverter: "unit-converter-urdu-guide",
    onlineTeleprompter: "online-teleprompter-urdu-guide",
    uuidGenerator: "uuid-generator-urdu-guide",
    timestampConverter: "unix-timestamp-converter-urdu-guide",
    jsonToCsv: "json-to-csv-converter-urdu-guide",
    regexTester: "regex-tester-urdu-guide",
    urlEncoder: "url-encoder-decoder-urdu-guide",
    utmLinkBuilder: "utm-link-builder-urdu-guide",
    onlineTimer: "online-timer-urdu-guide",
    instagramLineBreak: "instagram-line-break-urdu-guide",
    base64: "base64-encode-decode-urdu-guide",
    imageCompressor: "image-compressor-urdu-guide",
    pdfTools: "pdf-tools-urdu-guide",
    audioToText: "audio-to-text-converter-urdu-guide",
    backgroundRemover: "background-remover-urdu-guide",
    media: "video-tools-urdu-guide",
    seo: "seo-tools-urdu-guide",
    cleaner: "cliche-cleaner-urdu-guide",
    diff: "diff-checker-urdu-guide",
  };
  const TOOL_TO_ARTICLE_EN: Record<string, string> = {
    detector: "ai-detector-english-guide",
    citation: "citation-generator-english-guide",
    expander: "sentence-expander-english-guide",
    summarizer: "free-extractive-summarizer-honest-test",
    voiceTyping: "voice-typing-guide-speech-to-text",
    cvBuilder: "cv-builder-guide-free-resume",
    wordCounter: "word-counter-guide-accurate-counts",
    characterCounter: "character-counter-guide",
    textToSpeech: "text-to-speech-guide-read-aloud",
    typingTest: "typing-test-guide-wpm-accuracy",
    caseConverter: "case-converter-guide",
    passwordGenerator: "password-generator-guide",
    duplicateLines: "remove-duplicate-lines-guide",
    textRepeater: "text-repeater-guide",
    invisibleCharacter: "invisible-character-guide",
    wordFrequency: "word-frequency-counter-guide",
    readingTime: "reading-time-calculator-guide",
    slugGenerator: "slug-generator-guide",
    jsonFormatter: "json-formatter-guide",
    loremIpsum: "lorem-ipsum-generator-guide",
    daysBetween: "days-between-dates-guide",
    randomNumber: "random-number-generator-guide",
    invoiceGenerator: "invoice-generator-guide",
    imageResizer: "image-resizer-guide",
    imageConverter: "image-converter-guide",
    imageToText: "image-to-text-guide",
    pdfSplitter: "pdf-splitter-guide",
    usernameGenerator: "username-generator-guide",
    morseCodeTranslator: "morse-code-translator-guide",
    voiceRecorder: "online-voice-recorder-guide",
    onlineNotepad: "online-notepad-guide",
    unitConverter: "unit-converter-guide",
    onlineTeleprompter: "online-teleprompter-guide",
    uuidGenerator: "uuid-generator-guide",
    timestampConverter: "unix-timestamp-converter-guide",
    jsonToCsv: "json-to-csv-converter-guide",
    regexTester: "regex-tester-guide",
    urlEncoder: "url-encoder-decoder-guide",
    utmLinkBuilder: "utm-link-builder-guide",
    onlineTimer: "online-timer-stopwatch-guide",
    instagramLineBreak: "instagram-line-breaks-guide",
    base64: "base64-encode-decode-guide",
    imageCompressor: "image-compressor-email-wouldnt-send",
    pdfTools: "pdf-merge-deadline-guide",
    audioToText: "audio-to-text-converter-guide",
    backgroundRemover: "background-remover-guide",
    voiceCloner: "voice-cloner-guide",
    museAiHub: "muse-ai-availability-checker-guide",
    seo: "google-helpful-content-ai-seo-2026",
    humanizer: "how-to-make-chatgpt-text-sound-natural-guide",
  };
  const TOOL_TO_ARTICLE_ES: Record<string, string> = {
    humanizer: "humanizar-texto-ia-gratis-universidad-turnitin-guia",
    detector: "detector-ia-guia-espanol",
    citation: "generador-citas-guia-espanol",
    expander: "expansor-oraciones-guia-espanol",
    summarizer: "resumidor-texto-historia-estudiante",
    voiceTyping: "dictado-por-voz-guia",
    cvBuilder: "crear-curriculum-guia",
    wordCounter: "contador-palabras-guia",
    characterCounter: "contador-caracteres-guia",
    textToSpeech: "texto-a-voz-guia",
    typingTest: "prueba-velocidad-teclado-guia",
    caseConverter: "convertidor-mayusculas-guia",
    passwordGenerator: "generador-de-contrasenas-guia",
    duplicateLines: "eliminar-lineas-duplicadas-guia",
    textRepeater: "repetidor-de-texto-guia",
    invisibleCharacter: "caracter-invisible-guia",
    wordFrequency: "contador-frecuencia-palabras-guia",
    readingTime: "calculadora-tiempo-lectura-guia",
    slugGenerator: "generador-de-slugs-guia",
    jsonFormatter: "formateador-json-guia",
    loremIpsum: "generador-lorem-ipsum-guia",
    daysBetween: "dias-entre-fechas-guia",
    randomNumber: "generador-de-numeros-aleatorios-guia",
    invoiceGenerator: "generador-de-facturas-guia",
    imageResizer: "redimensionar-imagen-guia",
    imageConverter: "convertidor-imagenes-guia",
    imageToText: "imagen-a-texto-guia",
    pdfSplitter: "dividir-pdf-guia",
    usernameGenerator: "generador-usuarios-guia",
    morseCodeTranslator: "traductor-codigo-morse-guia",
    voiceRecorder: "grabadora-de-voz-online-guia",
    onlineNotepad: "bloc-de-notas-online-guia",
    unitConverter: "conversor-de-unidades-guia",
    onlineTeleprompter: "teleprompter-en-linea-guia",
    uuidGenerator: "generador-uuid-guia",
    timestampConverter: "convertidor-timestamp-unix-guia",
    jsonToCsv: "convertidor-json-a-csv-guia",
    regexTester: "probador-regex-guia",
    urlEncoder: "codificador-url-guia",
    utmLinkBuilder: "constructor-utm-guia",
    onlineTimer: "temporizador-online-cronometro-guia",
    instagramLineBreak: "saltos-de-linea-instagram-guia",
    base64: "codificar-decodificar-base64-guia",
    imageCompressor: "compresor-imagenes-truco-disenadores",
    pdfTools: "unir-pdfs-guia-practica",
    audioToText: "convertir-audio-a-texto-guia",
    backgroundRemover: "background-remover-guide-es",
    media: "herramientas-video-guia-espanol",
    seo: "herramientas-seo-guia-espanol",
    cleaner: "limpiador-cliches-guia-espanol",
  };
  const TOOL_TO_ARTICLE_DE: Record<string, string> = {
    humanizer: "chatgpt-texte-natuerlicher-klingen-lassen-guide",
    detector: "ki-detektor-anleitung-deutsch",
    citation: "zitat-generator-anleitung-deutsch",
    expander: "satz-erweiterer-anleitung-deutsch",
    summarizer: "extraktiv-abstraktiv-zusammenfassung-entscheidung",
    voiceTyping: "spracheingabe-anleitung",
    cvBuilder: "lebenslauf-erstellen-anleitung",
    wordCounter: "wortzaehler-anleitung",
    characterCounter: "zeichenzaehler-anleitung",
    textToSpeech: "text-zu-sprache-anleitung",
    typingTest: "tippgeschwindigkeit-test-anleitung",
    caseConverter: "gross-kleinschreibung-anleitung",
    passwordGenerator: "passwort-generator-anleitung",
    duplicateLines: "doppelte-zeilen-entfernen-anleitung",
    textRepeater: "text-wiederholer-anleitung",
    invisibleCharacter: "unsichtbares-zeichen-anleitung",
    wordFrequency: "worthaufigkeit-zaehler-anleitung",
    readingTime: "lesezeit-rechner-anleitung",
    slugGenerator: "slug-generator-anleitung",
    jsonFormatter: "json-formatierer-anleitung",
    loremIpsum: "lorem-ipsum-generator-anleitung",
    daysBetween: "tage-zwischen-daten-anleitung",
    randomNumber: "zufallszahlengenerator-anleitung",
    invoiceGenerator: "rechnung-generator-anleitung",
    imageResizer: "bildgroesse-aendern-anleitung",
    imageConverter: "bilder-konvertieren-anleitung",
    imageToText: "bild-zu-text-anleitung",
    pdfSplitter: "pdf-teilen-anleitung",
    usernameGenerator: "benutzername-generator-anleitung",
    morseCodeTranslator: "morse-code-uebersetzer-anleitung",
    voiceRecorder: "online-sprachrekorder-anleitung",
    onlineNotepad: "online-notizblock-anleitung",
    unitConverter: "einheitenrechner-anleitung",
    onlineTeleprompter: "online-teleprompter-anleitung",
    uuidGenerator: "uuid-generator-anleitung",
    timestampConverter: "unix-timestamp-converter-anleitung",
    jsonToCsv: "json-zu-csv-konverter-anleitung",
    regexTester: "regex-tester-anleitung",
    urlEncoder: "url-encoder-decoder-anleitung",
    utmLinkBuilder: "utm-link-builder-anleitung",
    onlineTimer: "online-timer-stoppuhr-anleitung",
    instagramLineBreak: "instagram-zeilenumbruch-anleitung",
    base64: "base64-kodieren-dekodieren-anleitung",
    imageCompressor: "warum-website-langsam-bilder-komprimieren",
    pdfTools: "pdfs-zusammenfuehren-anleitung",
    audioToText: "audio-in-text-umwandeln-anleitung",
    backgroundRemover: "background-remover-guide-de",
    media: "video-tools-anleitung-deutsch",
    seo: "seo-tools-anleitung-deutsch",
    cleaner: "klischee-reiniger-anleitung-deutsch",
    diff: "diff-checker-anleitung-deutsch",
  };
  const TOOL_TO_ARTICLE_FR: Record<string, string> = {
    humanizer: "comment-rendre-texte-chatgpt-plus-naturel-guide",
    detector: "detecteur-ia-guide-francais",
    citation: "generateur-citations-guide-francais",
    expander: "expanseur-phrases-guide-francais",
    summarizer: "resumeur-texte-guide-francais",
    voiceTyping: "saisie-vocale-guide",
    cvBuilder: "creer-cv-guide",
    wordCounter: "compteur-mots-guide",
    characterCounter: "compteur-caracteres-guide",
    textToSpeech: "synthese-vocale-guide",
    typingTest: "test-vitesse-frappe-guide",
    caseConverter: "convertisseur-casse-guide",
    passwordGenerator: "generateur-mot-de-passe-guide",
    duplicateLines: "supprimer-lignes-dupliquees-guide",
    textRepeater: "repeteur-de-texte-guide",
    invisibleCharacter: "caractere-invisible-guide",
    wordFrequency: "compteur-frequence-mots-guide",
    readingTime: "calculateur-temps-lecture-guide",
    slugGenerator: "generateur-de-slug-guide",
    jsonFormatter: "formateur-json-guide",
    loremIpsum: "generateur-lorem-ipsum-guide",
    daysBetween: "jours-entre-dates-guide",
    randomNumber: "generateur-de-nombres-aleatoires-guide",
    invoiceGenerator: "generateur-de-factures-guide",
    imageResizer: "redimensionner-image-guide",
    imageConverter: "convertisseur-image-guide",
    imageToText: "image-vers-texte-guide",
    pdfSplitter: "diviser-pdf-guide",
    usernameGenerator: "generateur-pseudo-guide",
    morseCodeTranslator: "traducteur-code-morse-guide",
    voiceRecorder: "enregistreur-vocal-en-ligne-guide",
    onlineNotepad: "bloc-notes-en-ligne-guide",
    unitConverter: "convertisseur-unites-guide",
    onlineTeleprompter: "teleprompter-en-ligne-guide",
    uuidGenerator: "generateur-uuid-guide",
    timestampConverter: "convertisseur-timestamp-unix-guide",
    jsonToCsv: "convertisseur-json-csv-guide",
    regexTester: "testeur-regex-guide",
    urlEncoder: "encodeur-url-guide",
    utmLinkBuilder: "generateur-utm-guide",
    onlineTimer: "minuteur-chronometre-en-ligne-guide",
    instagramLineBreak: "sauts-de-ligne-instagram-guide",
    base64: "encoder-decoder-base64-guide",
    imageCompressor: "compresseur-images-guide-francais",
    pdfTools: "outils-pdf-guide-francais",
    audioToText: "convertir-audio-en-texte-guide",
    backgroundRemover: "background-remover-guide-fr",
    media: "studio-video-guide-francais",
    seo: "outils-seo-guide-francais",
    cleaner: "nettoyeur-cliches-guide-francais",
    diff: "comparateur-diff-guide-francais",
  };
  const TOOL_TO_ARTICLE_TR: Record<string, string> = {
    humanizer: "chatgpt-metin-dogallastirma-rehberi",
    detector: "yapay-zeka-dedektoru-rehber",
    citation: "alinti-olusturucu-rehber",
    expander: "cumle-genisletici-rehber",
    summarizer: "metin-ozetleyici-rehber",
    voiceTyping: "sesli-yazma-rehberi",
    cvBuilder: "cv-olusturma-rehberi",
    wordCounter: "kelime-sayaci-rehberi",
    characterCounter: "karakter-sayaci-rehberi",
    textToSpeech: "metinden-sese-rehberi",
    typingTest: "yazma-hizi-testi-rehberi",
    caseConverter: "buyuk-kucuk-harf-rehberi",
    passwordGenerator: "sifre-olusturucu-rehberi",
    duplicateLines: "yinelenen-satirlari-kaldirma-rehberi",
    textRepeater: "metin-tekrarlayici-rehberi",
    invisibleCharacter: "gorunmez-karakter-rehberi",
    wordFrequency: "kelime-sikligi-sayaci-rehberi",
    readingTime: "okuma-suresi-hesaplayici-rehberi",
    slugGenerator: "slug-olusturucu-rehberi",
    jsonFormatter: "json-bicimlendirici-rehberi",
    loremIpsum: "lorem-ipsum-olusturucu-rehberi",
    daysBetween: "tarihler-arasi-gun-rehberi",
    randomNumber: "rastgele-sayi-uretme-rehberi",
    invoiceGenerator: "fatura-olusturucu-rehberi",
    imageResizer: "resim-boyutlandirma-rehberi",
    imageConverter: "resim-donusturucu-rehberi",
    imageToText: "resimden-metne-rehberi",
    pdfSplitter: "pdf-bolme-rehberi",
    usernameGenerator: "kullanici-adi-olusturucu-rehberi",
    morseCodeTranslator: "mors-kodu-cevirici-rehberi",
    voiceRecorder: "online-ses-kaydedici-rehberi",
    onlineNotepad: "online-not-defteri-rehberi",
    unitConverter: "birim-donusturucu-rehberi",
    onlineTeleprompter: "online-teleprompter-rehberi",
    uuidGenerator: "uuid-olusturucu-rehberi",
    timestampConverter: "unix-zaman-damgasi-donusturucu-rehberi",
    jsonToCsv: "json-csv-donusturucu-rehberi",
    regexTester: "regex-test-araci-rehberi",
    urlEncoder: "url-kodlayici-rehberi",
    utmLinkBuilder: "utm-baglanti-olusturucu-rehberi",
    onlineTimer: "online-zamanlayici-kronometre-rehberi",
    instagramLineBreak: "instagram-satir-atlama-rehberi",
    base64: "base64-kodlama-cozme-rehberi",
    imageCompressor: "resim-sikistirici-rehber",
    pdfTools: "pdf-araclari-rehber",
    audioToText: "sesi-metne-cevirme-rehberi",
    backgroundRemover: "background-remover-guide-tr",
    media: "video-studyosu-rehber",
    seo: "seo-araclari-rehber",
    cleaner: "klise-temizleyici-rehber",
    diff: "fark-karsilastirici-rehber",
  };
  const TOOL_TO_ARTICLE_JA: Record<string, string> = {
    humanizer: "chatgpt-bunsho-shizen-ni-naosu-guide",
    detector: "ai-kenshutsu-guide",
    citation: "inyo-generator-guide",
    expander: "bunsho-kakucho-guide",
    summarizer: "yoyaku-tool-guide",
    voiceTyping: "onsei-nyuryoku-guide",
    cvBuilder: "rirekisho-sakusei-guide",
    wordCounter: "word-counter-guide-ja",
    characterCounter: "character-counter-guide-ja",
    textToSpeech: "text-to-speech-guide-ja",
    typingTest: "typing-test-guide-ja",
    caseConverter: "case-converter-guide-ja",
    passwordGenerator: "password-generator-guide-ja",
    duplicateLines: "remove-duplicate-lines-guide-ja",
    textRepeater: "text-repeater-guide-ja",
    invisibleCharacter: "invisible-character-guide-ja",
    wordFrequency: "word-frequency-counter-guide-ja",
    readingTime: "reading-time-calculator-guide-ja",
    slugGenerator: "slug-generator-guide-ja",
    jsonFormatter: "json-formatter-guide-ja",
    loremIpsum: "lorem-ipsum-generator-guide-ja",
    daysBetween: "days-between-dates-guide-ja",
    randomNumber: "random-number-generator-guide-ja",
    invoiceGenerator: "invoice-generator-guide-ja",
    imageResizer: "image-resize-guide-ja",
    imageConverter: "image-converter-guide-ja",
    imageToText: "image-to-text-guide-ja",
    pdfSplitter: "pdf-splitter-guide-ja",
    usernameGenerator: "username-generator-guide-ja",
    morseCodeTranslator: "morse-code-translator-guide-ja",
    voiceRecorder: "online-voice-recorder-guide-ja",
    onlineNotepad: "online-notepad-guide-ja",
    unitConverter: "unit-converter-guide-ja",
    onlineTeleprompter: "online-teleprompter-guide-ja",
    uuidGenerator: "uuid-generator-guide-ja",
    timestampConverter: "unix-timestamp-converter-guide-ja",
    jsonToCsv: "json-to-csv-converter-guide-ja",
    regexTester: "regex-tester-guide-ja",
    urlEncoder: "url-encoder-decoder-guide-ja",
    utmLinkBuilder: "utm-link-builder-guide-ja",
    onlineTimer: "online-timer-stopwatch-guide-ja",
    instagramLineBreak: "instagram-line-break-guide-ja",
    base64: "base64-encode-decode-guide-ja",
    imageCompressor: "gazo-asshuku-guide",
    pdfTools: "pdf-tool-guide",
    audioToText: "audio-to-text-converter-guide-ja",
    backgroundRemover: "background-remover-guide-ja",
    media: "doga-studio-guide",
    seo: "seo-tool-guide",
    cleaner: "kurishe-jokyo-guide",
    diff: "diff-checker-guide",
  };
  const TOOL_TO_ARTICLE_IT: Record<string, string> = {
    humanizer: "umanizzatore-testo-guida-italiano",
    detector: "rilevatore-ia-guida-italiano",
    citation: "generatore-citazioni-guida-italiano",
    expander: "espansore-frasi-guida-italiano",
    summarizer: "riassuntore-testo-guida-italiano",
    voiceTyping: "dettatura-vocale-guida",
    cvBuilder: "creare-cv-guida",
    wordCounter: "contatore-parole-guida",
    characterCounter: "contatore-caratteri-guida",
    textToSpeech: "sintesi-vocale-guida",
    typingTest: "test-velocita-digitazione-guida",
    caseConverter: "convertitore-maiuscole-guida",
    passwordGenerator: "generatore-password-guida",
    duplicateLines: "rimuovere-linee-duplicate-guida",
    textRepeater: "ripetitore-testo-guida",
    invisibleCharacter: "carattere-invisibile-guida",
    wordFrequency: "contatore-frequenza-parole-guida",
    readingTime: "calcolatore-tempo-lettura-guida",
    slugGenerator: "generatore-di-slug-guida",
    jsonFormatter: "formattatore-json-guida",
    loremIpsum: "generatore-lorem-ipsum-guida",
    daysBetween: "giorni-tra-date-guida",
    randomNumber: "generatore-di-numeri-casuali-guida",
    invoiceGenerator: "generatore-di-fatture-guida",
    imageResizer: "ridimensiona-immagine-guida",
    imageConverter: "convertitore-immagini-guida",
    imageToText: "immagine-a-testo-guida",
    pdfSplitter: "dividere-pdf-guida",
    usernameGenerator: "generatore-username-guida",
    morseCodeTranslator: "traduttore-codice-morse-guida",
    voiceRecorder: "registratore-vocale-online-guida",
    onlineNotepad: "blocco-note-online-guida",
    unitConverter: "convertitore-unita-guida",
    onlineTeleprompter: "teleprompter-online-guida",
    uuidGenerator: "generatore-uuid-guida",
    timestampConverter: "convertitore-timestamp-unix-guida",
    jsonToCsv: "convertitore-json-csv-guida",
    regexTester: "tester-regex-guida",
    urlEncoder: "codificatore-url-guida",
    utmLinkBuilder: "generatore-utm-guida",
    onlineTimer: "timer-online-cronometro-guida",
    instagramLineBreak: "interruzioni-di-riga-instagram-guida",
    base64: "codifica-decodifica-base64-guida",
    imageCompressor: "compressore-immagini-guida-italiano",
    pdfTools: "strumenti-pdf-guida-italiano",
    audioToText: "convertire-audio-in-testo-guida",
    backgroundRemover: "background-remover-guide-it",
    media: "studio-video-guida-italiano",
    seo: "strumenti-seo-guida-italiano",
    cleaner: "pulitore-cliche-guida-italiano",
    diff: "confronta-diff-guida-italiano",
  };
  const TOOL_TO_ARTICLE_PT: Record<string, string> = {
    detector: "detector-ia-guia-portugues",
    citation: "gerador-citacoes-guia-portugues",
    expander: "expansor-frases-guia-portugues",
    summarizer: "resumidor-texto-guia-portugues",
    voiceTyping: "digitacao-por-voz-guia",
    cvBuilder: "criar-curriculo-guia",
    wordCounter: "contador-palavras-guia",
    characterCounter: "contador-de-caracteres-guia",
    textToSpeech: "texto-para-fala-guia",
    typingTest: "teste-velocidade-digitacao-guia",
    caseConverter: "conversor-maiusculas-guia",
    passwordGenerator: "gerador-de-senhas-guia",
    duplicateLines: "remover-linhas-duplicadas-guia",
    textRepeater: "repetir-texto-guia",
    invisibleCharacter: "caractere-invisivel-guia",
    wordFrequency: "contador-frequencia-palavras-guia",
    readingTime: "calculadora-tempo-leitura-guia",
    slugGenerator: "gerador-de-slug-guia",
    jsonFormatter: "formatador-json-guia",
    loremIpsum: "gerador-lorem-ipsum-guia",
    daysBetween: "dias-entre-datas-guia",
    randomNumber: "gerador-de-numeros-aleatorios-guia",
    invoiceGenerator: "gerador-de-faturas-guia",
    imageResizer: "redimensionar-imagem-guia",
    imageConverter: "conversor-imagem-guia",
    imageToText: "imagem-para-texto-guia",
    pdfSplitter: "dividir-pdf-guia-pt",
    usernameGenerator: "gerador-nomes-usuario-guia",
    morseCodeTranslator: "tradutor-codigo-morse-guia",
    voiceRecorder: "gravador-de-voz-online-guia-pt",
    onlineNotepad: "bloco-de-notas-online-guia",
    unitConverter: "conversor-de-unidades-guia",
    onlineTeleprompter: "teleprompter-online-guia",
    uuidGenerator: "gerador-uuid-guia",
    timestampConverter: "conversor-timestamp-unix-guia",
    jsonToCsv: "conversor-json-para-csv-guia",
    regexTester: "testador-regex-guia",
    urlEncoder: "codificador-url-guia",
    utmLinkBuilder: "construtor-utm-guia",
    onlineTimer: "cronometro-online-temporizador-guia",
    instagramLineBreak: "quebra-de-linha-instagram-guia",
    base64: "codificar-decodificar-base64-guia-pt",
    imageCompressor: "compressor-imagens-guia-portugues",
    pdfTools: "ferramentas-pdf-guia-portugues",
    audioToText: "converter-audio-em-texto-guia",
    backgroundRemover: "background-remover-guide-pt",
    media: "estudio-video-guia-portugues",
    seo: "ferramentas-seo-guia-portugues",
    cleaner: "limpador-cliches-guia-portugues",
    diff: "comparador-diff-guia-portugues",
  };
  const TOOL_TO_ARTICLE_NL: Record<string, string> = {
    humanizer: "tekst-humanizer-gids-nederlands",
    detector: "ai-detector-gids-nederlands",
    citation: "citatie-generator-gids-nederlands",
    expander: "zin-uitbreider-gids-nederlands",
    summarizer: "tekst-samenvatter-gids-nederlands",
    voiceTyping: "spraaktypen-gids",
    cvBuilder: "cv-maken-gids",
    wordCounter: "woordenteller-gids",
    characterCounter: "karakters-tellen-gids",
    textToSpeech: "tekst-naar-spraak-gids",
    typingTest: "typesnelheid-test-gids",
    caseConverter: "hoofdletter-converter-gids",
    passwordGenerator: "wachtwoordgenerator-gids",
    duplicateLines: "dubbele-regels-verwijderen-gids",
    textRepeater: "tekst-herhaler-gids",
    invisibleCharacter: "onzichtbaar-teken-gids",
    wordFrequency: "woordfrequentie-teller-gids",
    readingTime: "leestijd-calculator-gids",
    slugGenerator: "slug-generator-gids",
    jsonFormatter: "json-formatter-gids",
    loremIpsum: "lorem-ipsum-generator-gids",
    daysBetween: "dagen-tussen-datums-gids",
    randomNumber: "willekeurig-getalgenerator-gids",
    invoiceGenerator: "factuurgenerator-gids",
    imageResizer: "afbeelding-formaat-gids",
    imageConverter: "afbeelding-converter-gids",
    imageToText: "afbeelding-naar-tekst-gids",
    pdfSplitter: "pdf-splitsen-gids",
    usernameGenerator: "gebruikersnaam-generator-gids",
    morseCodeTranslator: "morsecode-vertaler-gids",
    voiceRecorder: "online-spraakrecorder-gids",
    onlineNotepad: "online-kladblok-gids",
    unitConverter: "eenheden-omrekenen-gids",
    onlineTeleprompter: "online-teleprompter-gids",
    uuidGenerator: "uuid-generator-gids",
    timestampConverter: "unix-timestamp-converter-gids",
    jsonToCsv: "json-naar-csv-converter-gids",
    regexTester: "regex-tester-gids",
    urlEncoder: "url-encoder-decoder-gids",
    utmLinkBuilder: "utm-linkbouwer-gids",
    onlineTimer: "online-timer-stopwatch-gids",
    instagramLineBreak: "instagram-regelafbreking-gids",
    base64: "base64-coderen-decoderen-gids",
    imageCompressor: "afbeelding-compressor-gids-nederlands",
    pdfTools: "pdf-tools-gids-nederlands",
    audioToText: "audio-naar-tekst-gids",
    backgroundRemover: "background-remover-guide-nl",
    media: "video-studio-gids-nederlands",
    seo: "seo-tools-gids-nederlands",
    cleaner: "cliche-verwijderaar-gids-nederlands",
    diff: "diff-vergelijker-gids-nederlands",
  };
  const TOOL_TO_ARTICLE_NO: Record<string, string> = {
    humanizer: "tekst-humanizer-guide-norsk",
    detector: "ai-detektor-guide-norsk",
    citation: "sitat-generator-guide-norsk",
    expander: "setnings-utvider-guide-norsk",
    summarizer: "tekst-sammendrag-guide-norsk",
    voiceTyping: "stemmeskriving-guide",
    cvBuilder: "cv-lage-guide",
    wordCounter: "ordteller-guide",
    characterCounter: "tegnteller-guide",
    textToSpeech: "tekst-til-tale-guide",
    typingTest: "skrivehastighet-test-guide",
    caseConverter: "stor-liten-bokstav-guide",
    passwordGenerator: "passord-generator-guide",
    duplicateLines: "fjerne-dupliserte-linjer-guide",
    textRepeater: "tekstgjentaker-guide",
    invisibleCharacter: "usynlig-tegn-guide",
    wordFrequency: "ordfrekvens-teller-guide",
    readingTime: "lesetid-kalkulator-guide",
    slugGenerator: "slug-generator-guide-no",
    jsonFormatter: "json-formatter-guide-no",
    loremIpsum: "lorem-ipsum-generator-guide-no",
    daysBetween: "dager-mellom-datoer-guide",
    randomNumber: "tilfeldig-tallgenerator-guide",
    invoiceGenerator: "fakturagenerator-guide",
    imageResizer: "bilde-endrings-guide",
    imageConverter: "bildekonverter-guide",
    imageToText: "bilde-til-tekst-guide",
    pdfSplitter: "del-pdf-guide",
    usernameGenerator: "brukernavn-generator-guide",
    morseCodeTranslator: "morsekode-oversetter-guide",
    voiceRecorder: "taleopptaker-pa-nett-guide",
    onlineNotepad: "nettbasert-notatblokk-guide",
    unitConverter: "enhetsomregner-guide",
    onlineTeleprompter: "teleprompter-pa-nett-guide",
    uuidGenerator: "uuid-generator-guide-no",
    timestampConverter: "unix-timestamp-converter-guide-no",
    jsonToCsv: "json-til-csv-omformer-guide",
    regexTester: "regex-tester-guide-no",
    urlEncoder: "url-encoder-decoder-guide-no",
    utmLinkBuilder: "utm-lenkebygger-guide-no",
    onlineTimer: "online-tidtaker-stoppeklokke-guide",
    instagramLineBreak: "instagram-linjeskift-guide",
    base64: "base64-koding-dekoding-guide",
    imageCompressor: "bilde-kompressor-guide-norsk",
    pdfTools: "pdf-verktoy-guide-norsk",
    audioToText: "lyd-til-tekst-veiledning",
    backgroundRemover: "background-remover-guide-no",
    media: "video-studio-guide-norsk",
    seo: "seo-verktoy-guide-norsk",
    cleaner: "klisje-fjerner-guide-norsk",
    diff: "diff-sammenligner-guide-norsk",
  };
  const articleMap = selectedLanguage === "ur" ? TOOL_TO_ARTICLE_UR : selectedLanguage === "es" ? TOOL_TO_ARTICLE_ES : selectedLanguage === "de" ? TOOL_TO_ARTICLE_DE : selectedLanguage === "fr" ? TOOL_TO_ARTICLE_FR : selectedLanguage === "tr" ? TOOL_TO_ARTICLE_TR : selectedLanguage === "ja" ? TOOL_TO_ARTICLE_JA : selectedLanguage === "it" ? TOOL_TO_ARTICLE_IT : selectedLanguage === "pt" ? TOOL_TO_ARTICLE_PT : selectedLanguage === "nl" ? TOOL_TO_ARTICLE_NL : selectedLanguage === "no" ? TOOL_TO_ARTICLE_NO : TOOL_TO_ARTICLE_EN;
  const guideSlug = articleMap[activePage];
  const guidePost = guideSlug ? findBlogPostBySlug(guideSlug) : null;

  return (
    <section className="w-full max-w-7xl mx-auto px-3 sm:px-6 lg:px-8 py-8 sm:py-10 border-t border-stone-200 overflow-hidden">
      {/* Related Guide Article Banner */}
      {guidePost && (
        <a
          href={`/${selectedLanguage}/blog/${guidePost.slug}/`}
          className="block mb-6 bg-gradient-to-r from-emerald-600 to-teal-600 rounded-2xl p-4 sm:p-5 text-white hover:shadow-lg transition-shadow"
        >
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center shrink-0">
              <BookOpen className="w-5 h-5" />
            </div>
            <div className="flex-1 min-w-0">
              <div className="text-xs font-semibold text-emerald-100 mb-0.5">
                📖 Guide
              </div>
              <div className="text-sm sm:text-base font-bold leading-snug line-clamp-2">
                {guidePost.title}
              </div>
            </div>
            <ArrowRight className="w-5 h-5 shrink-0" />
          </div>
        </a>
      )}
      {/* Section Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 mb-6">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-emerald-100 text-emerald-800 flex items-center gap-1">
              <Zap className="w-3 h-3 text-emerald-600" />
              ToolVena Tools
            </span>
            <span className="text-xs text-stone-500 font-medium">Free to Use</span>
          </div>
          <h3 className="text-xl sm:text-2xl font-extrabold text-stone-900 tracking-tight">
            {ot.heading || "Explore More Free Tools"}
          </h3>
          <p className="text-xs sm:text-sm text-stone-600">
            {ot.subheading || "Switch between ToolVena's writing, text, image, PDF and everyday tools."}
          </p>
        </div>
      </div>

      {/* 3 Tools Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        {displayTools.map((tool) => {
          const Icon = tool.icon;
          return (
            <div
              key={tool.id}
              onClick={() => onSelectPage(tool.id)}
              className={`bg-white rounded-2xl p-5 sm:p-6 border border-stone-200 shadow-sm transition-all duration-200 cursor-pointer flex flex-col justify-between group hover:-translate-y-1 hover:shadow-lg ${tool.cardBorder}`}
            >
              <div>
                {/* Top Row: Icon & Badge */}
                <div className="flex items-center justify-between mb-4">
                  <div className={`w-12 h-12 rounded-xl flex items-center justify-center shadow-md ${tool.iconBg}`}>
                    <Icon className="w-6 h-6 stroke-[2.2]" />
                  </div>
                  <span className={`text-[11px] font-extrabold px-2.5 py-1 rounded-full border ${tool.badgeColor}`}>
                    {tool.badge}
                  </span>
                </div>

                {/* Title & Subtitle */}
                <h4 className="text-base sm:text-lg font-bold text-stone-900 group-hover:text-emerald-700 transition-colors leading-snug">
                  {tool.title}
                </h4>
                <p className="text-xs text-stone-500 font-medium mt-0.5 mb-3">
                  {tool.subtitle}
                </p>

                {/* Description */}
                <p className="text-xs text-stone-600 leading-relaxed mb-4">
                  {tool.desc}
                </p>

                {/* Bullet Highlights */}
                <ul className="space-y-1.5 mb-5">
                  {tool.bullets.map((bullet, idx) => (
                    <li key={idx} className="flex items-center gap-2 text-xs text-stone-700">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Action Button */}
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  onSelectPage(tool.id);
                }}
                className={`w-full py-2.5 px-4 rounded-xl text-xs font-bold flex items-center justify-center gap-2 transition-all shadow-sm group-hover:shadow-md cursor-pointer ${tool.ctaBg}`}
              >
                <span>Launch {tool.title.split(" ")[0]}</span>
                <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
              </button>
            </div>
          );
        })}
      </div>
    </section>
  );
}
